/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { AlbusError } from "./albus-error.js";

export type ErrInvocationFailedData = {
  /**
   * Human-readable failure detail
   */
  message: string;
  /**
   * Failure classification: "crash" (unexpected exit or signal), "no_progress" (the harness stalled and was force-killed), or "interrupted" (the invocation could not continue), or "internal" (the invocation could not start).
   *
   * @remarks
   */
  kind: string;
};

export class ErrInvocationFailed extends AlbusError {
  /**
   * Failure classification: "crash" (unexpected exit or signal), "no_progress" (the harness stalled and was force-killed), or "interrupted" (the invocation could not continue), or "internal" (the invocation could not start).
   *
   * @remarks
   */
  kind: string;

  /** The original data that was passed to this error instance. */
  data$: ErrInvocationFailedData;

  constructor(
    err: ErrInvocationFailedData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.kind = err.kind;

    this.name = "ErrInvocationFailed";
  }
}

/** @internal */
export const ErrInvocationFailed$inboundSchema: z.ZodMiniType<
  ErrInvocationFailed,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    kind: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ErrInvocationFailed(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
