/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { AlbusError } from "./albus-error.js";

export type ErrForbiddenData = {
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * Machine-readable reason (e.g. "forbidden_not_admin").
   */
  code: string;
};

export class ErrForbidden extends AlbusError {
  /**
   * Machine-readable reason (e.g. "forbidden_not_admin").
   */
  code: string;

  /** The original data that was passed to this error instance. */
  data$: ErrForbiddenData;

  constructor(
    err: ErrForbiddenData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;

    this.name = "ErrForbidden";
  }
}

/** @internal */
export const ErrForbidden$inboundSchema: z.ZodMiniType<ErrForbidden, unknown> =
  z.pipe(
    z.object({
      message: types.string(),
      code: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ErrForbidden(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
