/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { AlbusError } from "./albus-error.js";

export type ErrNotFoundData = {
  /**
   * Human-readable error message
   */
  message: string;
};

export class ErrNotFound extends AlbusError {
  /** The original data that was passed to this error instance. */
  data$: ErrNotFoundData;

  constructor(
    err: ErrNotFoundData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ErrNotFound";
  }
}

/** @internal */
export const ErrNotFound$inboundSchema: z.ZodMiniType<ErrNotFound, unknown> = z
  .pipe(
    z.object({
      message: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ErrNotFound(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
