/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { AlbusError } from "./albus-error.js";

export type ErrUnauthorizedData = {
  /**
   * Human-readable error message
   */
  message: string;
};

export class ErrUnauthorized extends AlbusError {
  /** The original data that was passed to this error instance. */
  data$: ErrUnauthorizedData;

  constructor(
    err: ErrUnauthorizedData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ErrUnauthorized";
  }
}

/** @internal */
export const ErrUnauthorized$inboundSchema: z.ZodMiniType<
  ErrUnauthorized,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ErrUnauthorized(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
