/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { AlbusError } from "./albus-error.js";

export type HealthResponseErrorData = {
  status: string;
};

export class HealthResponseError extends AlbusError {
  status: string;

  /** The original data that was passed to this error instance. */
  data$: HealthResponseErrorData;

  constructor(
    err: HealthResponseErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;

    this.name = "HealthResponseError";
  }
}

/** @internal */
export const HealthResponseError$inboundSchema: z.ZodMiniType<
  HealthResponseError,
  unknown
> = z.pipe(
  z.object({
    status: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new HealthResponseError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
