/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsGetAgentRevision } from "../funcs/agents-get-agent-revision.js";
import { agentsGetAgent } from "../funcs/agents-get-agent.js";
import { agentsListAgents } from "../funcs/agents-list-agents.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Agents extends ClientSDK {
  /**
   * List agents
   *
   * @remarks
   * Lists the agents that have run in your organization, each with its latest revision.
   */
  async listAgents(
    options?: RequestOptions,
  ): Promise<models.ListAgentsResponse> {
    return unwrapAsync(agentsListAgents(
      this,
      options,
    ));
  }

  /**
   * Get an agent by name
   *
   * @remarks
   * Returns the agent with the given name, its current revision, and the list of all its revisions newest first.
   */
  async getAgent(
    request: operations.GetAgentRequest,
    options?: RequestOptions,
  ): Promise<models.Agent> {
    return unwrapAsync(agentsGetAgent(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a specific revision of an agent
   *
   * @remarks
   * Returns the full configuration of one revision of an agent — its model, tools, instructions, and MCP servers.
   */
  async getAgentRevision(
    request: operations.GetAgentRevisionRequest,
    options?: RequestOptions,
  ): Promise<models.AgentRevision> {
    return unwrapAsync(agentsGetAgentRevision(
      this,
      request,
      options,
    ));
  }
}
