/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authWhoami } from "../funcs/auth-whoami.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Auth extends ClientSDK {
  /**
   * Get the authenticated caller
   *
   * @remarks
   * Returns the signed-in user and their organizations, or the API key and its organization.
   */
  async whoami(
    options?: RequestOptions,
  ): Promise<models.WhoamiResponse> {
    return unwrapAsync(authWhoami(
      this,
      options,
    ));
  }
}
