/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authWhoami } from "../funcs/auth-whoami.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Auth extends ClientSDK {
  /**
   * Get the authenticated caller
   *
   * @remarks
   * Returns the caller a credential authenticates: a signed-in user with every organization they belong to and their roles in each, or the API key that signed the request, along with the organization it acts in.
   */
  async whoami(
    options?: RequestOptions,
  ): Promise<models.WhoamiResponse> {
    return unwrapAsync(authWhoami(
      this,
      options,
    ));
  }
}
