/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authWhoami } from "../funcs/auth-whoami.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Auth extends ClientSDK {
  /**
   * Get current user information
   *
   * @remarks
   * Returns the authenticated user along with every organization they belong to and their roles in each.
   */
  async whoami(
    options?: RequestOptions,
  ): Promise<models.WhoamiResponse> {
    return unwrapAsync(authWhoami(
      this,
      options,
    ));
  }
}
