/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { billingCreateCheckout } from "../funcs/billing-create-checkout.js";
import { billingGetCreditBalance } from "../funcs/billing-get-credit-balance.js";
import { billingListCreditLedger } from "../funcs/billing-list-credit-ledger.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Billing extends ClientSDK {
  /**
   * Buy prepaid credits
   *
   * @remarks
   * Starts a credit purchase for your organization. Returns the URL of a payment page to send the buyer's browser to; the credits are added to your balance once the payment completes there.
   */
  async createCheckout(
    request: models.CreateCheckoutRequest,
    options?: RequestOptions,
  ): Promise<models.CreateCheckoutResponse> {
    return unwrapAsync(billingCreateCheckout(
      this,
      request,
      options,
    ));
  }

  /**
   * Read your credit balance
   *
   * @remarks
   * Returns your organization's current prepaid credit balance in USD.
   */
  async getCreditBalance(
    request?: operations.GetCreditBalanceRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.CreditBalanceResponse> {
    return unwrapAsync(billingGetCreditBalance(
      this,
      request,
      options,
    ));
  }

  /**
   * List your credit history
   *
   * @remarks
   * Lists your organization's credit ledger, newest first: purchases, grants, usage charges, and adjustments, each with the signed USD amount it moved the balance by. Page with `after` and `limit`: pass the response's `next_cursor` as the next request's `after`, and keep requesting while `next_cursor` is present.
   */
  async listCreditLedger(
    request?: operations.ListCreditLedgerRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListCreditLedgerResponse> {
    return unwrapAsync(billingListCreditLedger(
      this,
      request,
      options,
    ));
  }
}
