/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { billingCreateCheckout } from "../funcs/billing-create-checkout.js";
import { billingGetCreditBalance } from "../funcs/billing-get-credit-balance.js";
import { billingListCreditLedger } from "../funcs/billing-list-credit-ledger.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Billing extends ClientSDK {
  /**
   * Buy prepaid credits
   *
   * @remarks
   * Creates a purchase and returns its payment URL. Credits are added when payment completes.
   */
  async createCheckout(
    request: models.CreateCheckoutRequest,
    options?: RequestOptions,
  ): Promise<models.CreateCheckoutResponse> {
    return unwrapAsync(billingCreateCheckout(
      this,
      request,
      options,
    ));
  }

  /**
   * Read your credit balance
   *
   * @remarks
   * Returns your organization's current prepaid credit balance in USD.
   */
  async getCreditBalance(
    options?: RequestOptions,
  ): Promise<models.CreditBalanceResponse> {
    return unwrapAsync(billingGetCreditBalance(
      this,
      options,
    ));
  }

  /**
   * List your credit history
   *
   * @remarks
   * Returns purchases, grants, usage charges, and adjustments newest first, with the signed USD amount of each balance change.
   */
  async listCreditLedger(
    request?: operations.ListCreditLedgerRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListCreditLedgerResponse> {
    return unwrapAsync(billingListCreditLedger(
      this,
      request,
      options,
    ));
  }
}
