/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { healthHealth } from "../funcs/health-health.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Health extends ClientSDK {
  /**
   * Health check endpoint
   *
   * @remarks
   * Returns 200 OK if the service is healthy
   */
  async health(
    options?: RequestOptions,
  ): Promise<models.HealthResponse> {
    return unwrapAsync(healthHealth(
      this,
      options,
    ));
  }
}
