/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invitesCreateInvite } from "../funcs/invites-create-invite.js";
import { invitesListInvites } from "../funcs/invites-list-invites.js";
import { invitesRevokeInvite } from "../funcs/invites-revoke-invite.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Invites extends ClientSDK {
  /**
   * List pending invitations
   *
   * @remarks
   * Returns unexpired invitations. Requires the admin role.
   */
  async listInvites(
    options?: RequestOptions,
  ): Promise<models.ListInvitesResponse> {
    return unwrapAsync(invitesListInvites(
      this,
      options,
    ));
  }

  /**
   * Invite a user by email
   *
   * @remarks
   * The invitation is accepted when the recipient signs in and expires after 14 days. Requires the admin role.
   */
  async createInvite(
    request: models.CreateInviteRequest,
    options?: RequestOptions,
  ): Promise<models.Invite> {
    return unwrapAsync(invitesCreateInvite(
      this,
      request,
      options,
    ));
  }

  /**
   * Revoke a pending invitation
   *
   * @remarks
   * Requires the admin role.
   */
  async revokeInvite(
    request: operations.RevokeInviteRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(invitesRevokeInvite(
      this,
      request,
      options,
    ));
  }
}
