/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invitesCreateInvite } from "../funcs/invites-create-invite.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Invites extends ClientSDK {
  /**
   * Invite a user by email
   *
   * @remarks
   * Creates a pending invitation for an email address. Omit organization_id to invite the user as the founder of a new organization that is created on their first sign-in; provide it to invite them into an existing organization. The invitation is redeemed automatically the first time the invitee signs in with that email.
   */
  async createInvite(
    request: models.CreateInviteRequest,
    options?: RequestOptions,
  ): Promise<models.Invite> {
    return unwrapAsync(invitesCreateInvite(
      this,
      request,
      options,
    ));
  }
}
