/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { memoriesDeleteMemoryGroup } from "../funcs/memories-delete-memory-group.js";
import { memoriesDeleteMemory } from "../funcs/memories-delete-memory.js";
import { memoriesListMemories } from "../funcs/memories-list-memories.js";
import { memoriesListMemoryGroups } from "../funcs/memories-list-memory-groups.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Memories extends ClientSDK {
  /**
   * List memory groups
   *
   * @remarks
   * Returns memory groups ordered by key, with each group's active memory count.
   */
  async listMemoryGroups(
    request?: operations.ListMemoryGroupsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListMemoryGroupsResponse> {
    return unwrapAsync(memoriesListMemoryGroups(
      this,
      request,
      options,
    ));
  }

  /**
   * List a group's memories
   *
   * @remarks
   * Returns active memories newest first. Replaced memories are omitted.
   */
  async listMemories(
    request: operations.ListMemoriesRequest,
    options?: RequestOptions,
  ): Promise<models.ListMemoriesResponse> {
    return unwrapAsync(memoriesListMemories(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a group's memories
   *
   * @remarks
   * Removes every memory in the group. Agents can add new memories later.
   */
  async deleteMemoryGroup(
    request: operations.DeleteMemoryGroupRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(memoriesDeleteMemoryGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete one memory
   *
   * @remarks
   * Permanently removes the memory from the group.
   */
  async deleteMemory(
    request: operations.DeleteMemoryRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(memoriesDeleteMemory(
      this,
      request,
      options,
    ));
  }
}
