/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { memoriesDeleteMemoryGroup } from "../funcs/memories-delete-memory-group.js";
import { memoriesDeleteMemory } from "../funcs/memories-delete-memory.js";
import { memoriesListMemories } from "../funcs/memories-list-memories.js";
import { memoriesListMemoryGroups } from "../funcs/memories-list-memory-groups.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Memories extends ClientSDK {
  /**
   * List memory groups
   *
   * @remarks
   * Lists the memory groups of your organization, ordered by key: every `memory.group` value an agent has run with, along with how many memories agents in the group currently read. Read a group's memories with `GET /memorygroups/{group}`.
   *
   * Page with `after` and `limit`: pass the response's `next_cursor` as the next request's `after`, and keep requesting while `next_cursor` is present — you have reached the end when it is absent.
   */
  async listMemoryGroups(
    request?: operations.ListMemoryGroupsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListMemoryGroupsResponse> {
    return unwrapAsync(memoriesListMemoryGroups(
      this,
      request,
      options,
    ));
  }

  /**
   * List a group's memories
   *
   * @remarks
   * Lists the memories of one memory group, newest first: both the memories agents currently read and those a later memory has replaced. A group nothing has been remembered in yet is an empty list, not an error.
   *
   * Page with `after` and `limit`: pass the response's `next_cursor` as the next request's `after`, and keep requesting while `next_cursor` is present — you have reached the end when it is absent.
   */
  async listMemories(
    request: operations.ListMemoriesRequest,
    options?: RequestOptions,
  ): Promise<models.ListMemoriesResponse> {
    return unwrapAsync(memoriesListMemories(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a group's memories
   *
   * @remarks
   * Deletes every memory of one memory group. Agents bound to the group remember nothing from before the call and can remember again after it. A group that holds no memories is deleted just the same, so the call is safe to repeat.
   */
  async deleteMemoryGroup(
    request: operations.DeleteMemoryGroupRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(memoriesDeleteMemoryGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete one memory
   *
   * @remarks
   * Deletes one memory of a memory group. Agents bound to the group stop reading it, and the deletion is permanent. A memory the group does not hold is a `404`.
   */
  async deleteMemory(
    request: operations.DeleteMemoryRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(memoriesDeleteMemory(
      this,
      request,
      options,
    ));
  }
}
