/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modelsListModels } from "../funcs/models-list-models.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Models extends ClientSDK {
  /**
   * List models
   *
   * @remarks
   * Lists the models available to run agents on, each with the provider that serves it.
   */
  async listModels(
    request?: operations.ListModelsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListModelsResponse> {
    return unwrapAsync(modelsListModels(
      this,
      request,
      options,
    ));
  }
}
