/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modelsListModels } from "../funcs/models-list-models.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Models extends ClientSDK {
  /**
   * List models
   *
   * @remarks
   * Returns available models and their providers.
   */
  async listModels(
    options?: RequestOptions,
  ): Promise<models.ListModelsResponse> {
    return unwrapAsync(modelsListModels(
      this,
      options,
    ));
  }
}
