/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationGetOrganization } from "../funcs/organization-get-organization.js";
import { organizationListOrganizationMembers } from "../funcs/organization-list-organization-members.js";
import { organizationRemoveOrganizationMember } from "../funcs/organization-remove-organization-member.js";
import { organizationSetOrganizationMemberRole } from "../funcs/organization-set-organization-member-role.js";
import { organizationUpdateOrganization } from "../funcs/organization-update-organization.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Organization extends ClientSDK {
  /**
   * Get the current organization
   */
  async getOrganization(
    options?: RequestOptions,
  ): Promise<models.Organization> {
    return unwrapAsync(organizationGetOrganization(
      this,
      options,
    ));
  }

  /**
   * Rename the current organization
   *
   * @remarks
   * Requires the admin role.
   */
  async updateOrganization(
    request: models.UpdateOrganizationRequest,
    options?: RequestOptions,
  ): Promise<models.Organization> {
    return unwrapAsync(organizationUpdateOrganization(
      this,
      request,
      options,
    ));
  }

  /**
   * List organization members
   */
  async listOrganizationMembers(
    options?: RequestOptions,
  ): Promise<models.ListOrganizationMembersResponse> {
    return unwrapAsync(organizationListOrganizationMembers(
      this,
      options,
    ));
  }

  /**
   * Remove an organization member
   *
   * @remarks
   * Requires the admin role. The last admin cannot be removed.
   */
  async removeOrganizationMember(
    request: operations.RemoveOrganizationMemberRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(organizationRemoveOrganizationMember(
      this,
      request,
      options,
    ));
  }

  /**
   * Set an organization member's role
   *
   * @remarks
   * Requires the admin role. The last admin cannot be demoted.
   */
  async setOrganizationMemberRole(
    request: operations.SetOrganizationMemberRoleRequest,
    options?: RequestOptions,
  ): Promise<models.OrganizationMember> {
    return unwrapAsync(organizationSetOrganizationMemberRole(
      this,
      request,
      options,
    ));
  }
}
