/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Auth } from "./auth.js";
import { Health } from "./health.js";
import { Invites } from "./invites.js";
import { Secrets } from "./secrets.js";
import { Sessions } from "./sessions.js";
import { Tokens } from "./tokens.js";

export class Albus extends ClientSDK {
  private _secrets?: Secrets;
  get secrets(): Secrets {
    return (this._secrets ??= new Secrets(this._options));
  }

  private _sessions?: Sessions;
  get sessions(): Sessions {
    return (this._sessions ??= new Sessions(this._options));
  }

  private _tokens?: Tokens;
  get tokens(): Tokens {
    return (this._tokens ??= new Tokens(this._options));
  }

  private _health?: Health;
  get health(): Health {
    return (this._health ??= new Health(this._options));
  }

  private _auth?: Auth;
  get auth(): Auth {
    return (this._auth ??= new Auth(this._options));
  }

  private _invites?: Invites;
  get invites(): Invites {
    return (this._invites ??= new Invites(this._options));
  }
}
