/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { secretsCreateSecret } from "../funcs/secrets-create-secret.js";
import { secretsDeleteSecret } from "../funcs/secrets-delete-secret.js";
import { secretsGetSecret } from "../funcs/secrets-get-secret.js";
import { secretsListSecrets } from "../funcs/secrets-list-secrets.js";
import { secretsUpdateSecret } from "../funcs/secrets-update-secret.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Secrets extends ClientSDK {
  /**
   * List all secrets
   */
  async listSecrets(
    options?: RequestOptions,
  ): Promise<models.ListSecretsResponse> {
    return unwrapAsync(secretsListSecrets(
      this,
      options,
    ));
  }

  /**
   * Create a secret
   */
  async createSecret(
    request: models.CreateSecretRequest,
    options?: RequestOptions,
  ): Promise<models.Secret> {
    return unwrapAsync(secretsCreateSecret(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a secret by name
   */
  async getSecret(
    request: operations.GetSecretRequest,
    options?: RequestOptions,
  ): Promise<models.Secret> {
    return unwrapAsync(secretsGetSecret(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a secret by name
   */
  async updateSecret(
    request: operations.UpdateSecretRequest,
    options?: RequestOptions,
  ): Promise<models.Secret> {
    return unwrapAsync(secretsUpdateSecret(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a secret by name
   */
  async deleteSecret(
    request: operations.DeleteSecretRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(secretsDeleteSecret(
      this,
      request,
      options,
    ));
  }
}
