/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionsCancelSession } from "../funcs/sessions-cancel-session.js";
import { sessionsDeleteSession } from "../funcs/sessions-delete-session.js";
import { sessionsGetSessionAudit } from "../funcs/sessions-get-session-audit.js";
import { sessionsGetSession } from "../funcs/sessions-get-session.js";
import { sessionsListSessions } from "../funcs/sessions-list-sessions.js";
import { sessionsRunSession } from "../funcs/sessions-run-session.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Sessions extends ClientSDK {
  /**
   * List sessions
   *
   * @remarks
   * Lists your organization's sessions, most recently used first. Filter by agent name, agent revision, invocation state, time window, or an invocation it ran: a session matches when any of its invocations does, and a filtered listing is ordered by each session's most recent matching invocation. A filter that matches nothing returns an empty page rather than an error.
   *
   * Page with `after` and `limit`: pass the response's `next_cursor` as the next request's `after`, and keep requesting while `next_cursor` is present — you have reached the end when it is absent. A page can hold fewer sessions than `limit`, or none at all, and still have a `next_cursor`; a short page is not the end of the results.
   *
   * A listing covers the window given by `since` and `until`, and omitting `since` searches the last 31 days. The window is fixed when the first page is requested, so paging with `after` keeps returning results from the window that page used: `after` carries that window and the filters it was made with, so send it with no filters, or with every filter repeated exactly, and expect a `400` otherwise.
   */
  async listSessions(
    request?: operations.ListSessionsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListSessionsResponse> {
    return unwrapAsync(sessionsListSessions(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a session with its messages
   *
   * @remarks
   * Returns the session's metadata and a page of its messages ordered by cursor ascending. Use `after` and `limit` to page through messages.
   */
  async getSession(
    request: operations.GetSessionRequest,
    options?: RequestOptions,
  ): Promise<models.SessionResponse> {
    return unwrapAsync(sessionsGetSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Run or resume a session
   *
   * @remarks
   * Runs the session with the given ID, creating it if it does not exist and resuming it otherwise. Each call is a single invocation, optionally named by the Idempotency-Key header, whose value is the invocation's key. Supplying a key makes the call safe to retry: retrying with the same key and an identical body re-attaches to the in-flight invocation and returns its current state; a differing body for the same key returns 409; a new key while another invocation is still running returns 423. Omitting the header starts a fresh, non-idempotent invocation each time; the server generates a key and returns it in the Idempotency-Key response header.
   *
   * With `wait_timeout_seconds` the request long-polls: it blocks until the invocation's assistant response is available and returns it in `message`. Omit it to wait up to 30 minutes, or pass 0 to return as soon as the invocation is accepted. A positive value bounds the wait in seconds; if it elapses first the request fails with 504 and a JSON body, letting the client distinguish an expected server-side timeout from a transport error; the client may retry.
   */
  async runSession(
    request: operations.RunSessionRequest,
    options?: RequestOptions,
  ): Promise<operations.RunSessionResponse> {
    return unwrapAsync(sessionsRunSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a session
   */
  async deleteSession(
    request: operations.DeleteSessionRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(sessionsDeleteSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel a session's running invocation
   *
   * @remarks
   * Requests cancellation of the invocation currently running for the session. Cancellation is asynchronous: the call returns once the request is accepted, and the invocation resolves as canceled shortly after, unlocking the session for new invocations. A request waiting on the invocation receives its terminal outcome. Returns 409 when the session has no invocation running.
   */
  async cancelSession(
    request: operations.CancelSessionRequest,
    options?: RequestOptions,
  ): Promise<models.CancelSessionResponse> {
    return unwrapAsync(sessionsCancelSession(
      this,
      request,
      options,
    ));
  }

  /**
   * List a session's audit log
   *
   * @remarks
   * Returns the session's audit log — an immutable, time-ordered record of what happened during its invocations (LLM calls, tool results, and invocation outcomes). Events are ordered by the time they occurred. Use `after` and `limit` to page through them; pass the response's `next_cursor` as the next request's `after` to fetch the following page.
   */
  async getSessionAudit(
    request: operations.GetSessionAuditRequest,
    options?: RequestOptions,
  ): Promise<models.ListAuditEventsResponse> {
    return unwrapAsync(sessionsGetSessionAudit(
      this,
      request,
      options,
    ));
  }
}
