/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionsCancelSession } from "../funcs/sessions-cancel-session.js";
import { sessionsDeleteSession } from "../funcs/sessions-delete-session.js";
import { sessionsGetSessionAudit } from "../funcs/sessions-get-session-audit.js";
import { sessionsGetSession } from "../funcs/sessions-get-session.js";
import { sessionsListSessions } from "../funcs/sessions-list-sessions.js";
import { sessionsRunSession } from "../funcs/sessions-run-session.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Sessions extends ClientSDK {
  /**
   * List sessions
   *
   * @remarks
   * Returns sessions ordered by their most recent matching invocation.
   */
  async listSessions(
    request?: operations.ListSessionsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListSessionsResponse> {
    return unwrapAsync(sessionsListSessions(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a session with its messages
   *
   * @remarks
   * Returns session metadata and messages in chronological order.
   */
  async getSession(
    request: operations.GetSessionRequest,
    options?: RequestOptions,
  ): Promise<models.SessionResponse> {
    return unwrapAsync(sessionsGetSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Run or resume a session
   *
   * @remarks
   * Starts a new session or continues an existing one with another agent invocation.
   */
  async runSession(
    request: operations.RunSessionRequest,
    options?: RequestOptions,
  ): Promise<operations.RunSessionResponse> {
    return unwrapAsync(sessionsRunSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a session
   */
  async deleteSession(
    request: operations.DeleteSessionRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(sessionsDeleteSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel a session's running invocation
   *
   * @remarks
   * Requests asynchronous cancellation and returns once accepted.
   */
  async cancelSession(
    request: operations.CancelSessionRequest,
    options?: RequestOptions,
  ): Promise<models.CancelSessionResponse> {
    return unwrapAsync(sessionsCancelSession(
      this,
      request,
      options,
    ));
  }

  /**
   * List a session's audit log
   *
   * @remarks
   * Returns an immutable record of session events in chronological order.
   */
  async getSessionAudit(
    request: operations.GetSessionAuditRequest,
    options?: RequestOptions,
  ): Promise<models.ListAuditEventsResponse> {
    return unwrapAsync(sessionsGetSessionAudit(
      this,
      request,
      options,
    ));
  }
}
