/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionsDeleteSession } from "../funcs/sessions-delete-session.js";
import { sessionsGetSessionAudit } from "../funcs/sessions-get-session-audit.js";
import { sessionsGetSession } from "../funcs/sessions-get-session.js";
import { sessionsListSessions } from "../funcs/sessions-list-sessions.js";
import { sessionsRunSession } from "../funcs/sessions-run-session.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Sessions extends ClientSDK {
  /**
   * List all sessions
   */
  async listSessions(
    options?: RequestOptions,
  ): Promise<models.ListSessionsResponse> {
    return unwrapAsync(sessionsListSessions(
      this,
      options,
    ));
  }

  /**
   * Get a session with its messages
   *
   * @remarks
   * Returns the session's metadata and a page of its messages ordered by cursor ascending. Use `after` and `limit` to page through messages.
   */
  async getSession(
    request: operations.GetSessionRequest,
    options?: RequestOptions,
  ): Promise<models.SessionResponse> {
    return unwrapAsync(sessionsGetSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Run or resume a session
   *
   * @remarks
   * Runs the session with the given ID, creating it if it does not exist and resuming it otherwise. Each call is a single invocation, optionally identified by the Idempotency-Key header. Supplying a key makes the call safe to retry: retrying with the same key and an identical body re-attaches to the in-flight invocation and returns its current state; a differing body for the same key returns 409; a new key while another invocation is still running returns 423. Omitting the header starts a fresh, non-idempotent invocation each time; the server generates a key and returns it in the Idempotency-Key response header.
   *
   * With `wait_timeout_seconds` the request long-polls: it blocks until the invocation's assistant response is available and returns it in `messages`. Omit it to wait up to 30 minutes, or pass 0 to return as soon as the invocation is accepted. A positive value bounds the wait in seconds; if it elapses first the request fails with 504 and a JSON body, letting the client distinguish an expected server-side timeout from a transport error; the client may retry.
   */
  async runSession(
    request: operations.RunSessionRequest,
    options?: RequestOptions,
  ): Promise<operations.RunSessionResponse> {
    return unwrapAsync(sessionsRunSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a session
   */
  async deleteSession(
    request: operations.DeleteSessionRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(sessionsDeleteSession(
      this,
      request,
      options,
    ));
  }

  /**
   * List a session's audit log
   *
   * @remarks
   * Returns the session's audit log — an immutable, time-ordered record of what happened during its agent runs (LLM calls, tool results, and run outcomes). Events are ordered by the time they occurred. Use `after` and `limit` to page through them; pass the response's `next_cursor` as the next request's `after` to fetch the following page.
   */
  async getSessionAudit(
    request: operations.GetSessionAuditRequest,
    options?: RequestOptions,
  ): Promise<models.ListAuditEventsResponse> {
    return unwrapAsync(sessionsGetSessionAudit(
      this,
      request,
      options,
    ));
  }
}
