/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tokensCreateToken } from "../funcs/tokens-create-token.js";
import { tokensDeleteToken } from "../funcs/tokens-delete-token.js";
import { tokensGetToken } from "../funcs/tokens-get-token.js";
import { tokensListTokens } from "../funcs/tokens-list-tokens.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tokens extends ClientSDK {
  /**
   * List all API tokens. Never returns token values, only metadata.
   */
  async listTokens(
    options?: RequestOptions,
  ): Promise<models.ListTokensResponse> {
    return unwrapAsync(tokensListTokens(
      this,
      options,
    ));
  }

  /**
   * Create an API token. The token value is returned only in this response.
   */
  async createToken(
    request: models.CreateTokenRequest,
    options?: RequestOptions,
  ): Promise<models.CreateTokenResponse> {
    return unwrapAsync(tokensCreateToken(
      this,
      request,
      options,
    ));
  }

  /**
   * Get token metadata by ID. Never returns the token value.
   */
  async getToken(
    request: operations.GetTokenRequest,
    options?: RequestOptions,
  ): Promise<models.Token> {
    return unwrapAsync(tokensGetToken(
      this,
      request,
      options,
    ));
  }

  /**
   * Revoke an API token by ID
   */
  async deleteToken(
    request: operations.DeleteTokenRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(tokensDeleteToken(
      this,
      request,
      options,
    ));
  }
}
