/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tracesGetTrace } from "../funcs/traces-get-trace.js";
import { tracesListTraces } from "../funcs/traces-list-traces.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Traces extends ClientSDK {
  /**
   * Search traces
   *
   * @remarks
   * Returns invocations newest first, without their spans. Running invocations are included.
   */
  async listTraces(
    request?: operations.ListTracesRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListTracesResponse> {
    return unwrapAsync(tracesListTraces(
      this,
      request,
      options,
    ));
  }

  /**
   * Get one invocation's trace
   *
   * @remarks
   * Returns an invocation and its spans in chronological order. Spans may appear shortly after they occur and expire before the invocation does.
   */
  async getTrace(
    request: operations.GetTraceRequest,
    options?: RequestOptions,
  ): Promise<operations.GetTraceResponse> {
    return unwrapAsync(tracesGetTrace(
      this,
      request,
      options,
    ));
  }
}
