/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CancelSessionGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type CancelSessionRequest = {
  /**
   * Client-provided session identifier. Use the same value across requests to continue the same agent session.
   */
  id: string;
};

/** @internal */
export type CancelSessionRequest$Outbound = {
  id: string;
};

/** @internal */
export const CancelSessionRequest$outboundSchema: z.ZodMiniType<
  CancelSessionRequest$Outbound,
  CancelSessionRequest
> = z.object({
  id: z.string(),
});

export function cancelSessionRequestToJSON(
  cancelSessionRequest: CancelSessionRequest,
): string {
  return JSON.stringify(
    CancelSessionRequest$outboundSchema.parse(cancelSessionRequest),
  );
}
