/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type CreateSecretGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};
