/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteTokenRequest = {
  /**
   * The token's lookup ID.
   */
  id: string;
};

/** @internal */
export type DeleteTokenRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteTokenRequest$outboundSchema: z.ZodMiniType<
  DeleteTokenRequest$Outbound,
  DeleteTokenRequest
> = z.object({
  id: z.string(),
});

export function deleteTokenRequestToJSON(
  deleteTokenRequest: DeleteTokenRequest,
): string {
  return JSON.stringify(
    DeleteTokenRequest$outboundSchema.parse(deleteTokenRequest),
  );
}
