/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteSessionRequest = {
  /**
   * Client-provided session identifier. Reuse it to continue the session.
   *
   * @remarks
   */
  id: string;
};

/** @internal */
export type DeleteSessionRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteSessionRequest$outboundSchema: z.ZodMiniType<
  DeleteSessionRequest$Outbound,
  DeleteSessionRequest
> = z.object({
  id: z.string(),
});

export function deleteSessionRequestToJSON(
  deleteSessionRequest: DeleteSessionRequest,
): string {
  return JSON.stringify(
    DeleteSessionRequest$outboundSchema.parse(deleteSessionRequest),
  );
}
