/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteSessionGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type DeleteSessionRequest = {
  /**
   * Client-provided session identifier. Use the same value across requests to continue the same agent session.
   */
  id: string;
};

/** @internal */
export type DeleteSessionRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteSessionRequest$outboundSchema: z.ZodMiniType<
  DeleteSessionRequest$Outbound,
  DeleteSessionRequest
> = z.object({
  id: z.string(),
});

export function deleteSessionRequestToJSON(
  deleteSessionRequest: DeleteSessionRequest,
): string {
  return JSON.stringify(
    DeleteSessionRequest$outboundSchema.parse(deleteSessionRequest),
  );
}
