/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteSecretGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type DeleteSecretRequest = {
  name: string;
};

/** @internal */
export type DeleteSecretRequest$Outbound = {
  name: string;
};

/** @internal */
export const DeleteSecretRequest$outboundSchema: z.ZodMiniType<
  DeleteSecretRequest$Outbound,
  DeleteSecretRequest
> = z.object({
  name: z.string(),
});

export function deleteSecretRequestToJSON(
  deleteSecretRequest: DeleteSecretRequest,
): string {
  return JSON.stringify(
    DeleteSecretRequest$outboundSchema.parse(deleteSecretRequest),
  );
}
