/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteSecretRequest = {
  name: string;
};

/** @internal */
export type DeleteSecretRequest$Outbound = {
  name: string;
};

/** @internal */
export const DeleteSecretRequest$outboundSchema: z.ZodMiniType<
  DeleteSecretRequest$Outbound,
  DeleteSecretRequest
> = z.object({
  name: z.string(),
});

export function deleteSecretRequestToJSON(
  deleteSecretRequest: DeleteSecretRequest,
): string {
  return JSON.stringify(
    DeleteSecretRequest$outboundSchema.parse(deleteSecretRequest),
  );
}
