/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteMemoryGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type DeleteMemoryRequest = {
  /**
   * The memory group to read or delete — the `memory.group` value the agents sharing those memories run with.
   *
   * @remarks
   */
  group: string;
  /**
   * The memory's identifier, as returned by `GET /memorygroups/{group}`.
   *
   * @remarks
   */
  id: string;
};

/** @internal */
export type DeleteMemoryRequest$Outbound = {
  group: string;
  id: string;
};

/** @internal */
export const DeleteMemoryRequest$outboundSchema: z.ZodMiniType<
  DeleteMemoryRequest$Outbound,
  DeleteMemoryRequest
> = z.object({
  group: z.string(),
  id: z.string(),
});

export function deleteMemoryRequestToJSON(
  deleteMemoryRequest: DeleteMemoryRequest,
): string {
  return JSON.stringify(
    DeleteMemoryRequest$outboundSchema.parse(deleteMemoryRequest),
  );
}
