/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteMemoryGroupRequest = {
  /**
   * Memory group to read or delete, matching the agent's `memory.group`.
   *
   * @remarks
   */
  group: string;
};

/** @internal */
export type DeleteMemoryGroupRequest$Outbound = {
  group: string;
};

/** @internal */
export const DeleteMemoryGroupRequest$outboundSchema: z.ZodMiniType<
  DeleteMemoryGroupRequest$Outbound,
  DeleteMemoryGroupRequest
> = z.object({
  group: z.string(),
});

export function deleteMemoryGroupRequestToJSON(
  deleteMemoryGroupRequest: DeleteMemoryGroupRequest,
): string {
  return JSON.stringify(
    DeleteMemoryGroupRequest$outboundSchema.parse(deleteMemoryGroupRequest),
  );
}
