/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteMemoryGroupGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type DeleteMemoryGroupRequest = {
  /**
   * The memory group to read or delete — the `memory.group` value the agents sharing those memories run with.
   *
   * @remarks
   */
  group: string;
};

/** @internal */
export type DeleteMemoryGroupRequest$Outbound = {
  group: string;
};

/** @internal */
export const DeleteMemoryGroupRequest$outboundSchema: z.ZodMiniType<
  DeleteMemoryGroupRequest$Outbound,
  DeleteMemoryGroupRequest
> = z.object({
  group: z.string(),
});

export function deleteMemoryGroupRequestToJSON(
  deleteMemoryGroupRequest: DeleteMemoryGroupRequest,
): string {
  return JSON.stringify(
    DeleteMemoryGroupRequest$outboundSchema.parse(deleteMemoryGroupRequest),
  );
}
