/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetAgentRevisionRequest = {
  /**
   * The agent's name.
   */
  name: string;
  /**
   * The agent revision to fetch.
   */
  revision: string;
};

/** @internal */
export type GetAgentRevisionRequest$Outbound = {
  name: string;
  revision: string;
};

/** @internal */
export const GetAgentRevisionRequest$outboundSchema: z.ZodMiniType<
  GetAgentRevisionRequest$Outbound,
  GetAgentRevisionRequest
> = z.object({
  name: z.string(),
  revision: z.string(),
});

export function getAgentRevisionRequestToJSON(
  getAgentRevisionRequest: GetAgentRevisionRequest,
): string {
  return JSON.stringify(
    GetAgentRevisionRequest$outboundSchema.parse(getAgentRevisionRequest),
  );
}
