/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Which attempts to return spans for. `final`, the default, returns only the spans of the latest attempt — the one that produced the invocation's outcome, or the one still in flight; `all` also returns the spans of the attempts before it, each marked `superseded`. Either way `attempts` in the response lists every attempt that ran.
 *
 * @remarks
 */
export const Attempts = {
  Final: "final",
  All: "all",
} as const;
/**
 * Which attempts to return spans for. `final`, the default, returns only the spans of the latest attempt — the one that produced the invocation's outcome, or the one still in flight; `all` also returns the spans of the attempts before it, each marked `superseded`. Either way `attempts` in the response lists every attempt that ran.
 *
 * @remarks
 */
export type Attempts = ClosedEnum<typeof Attempts>;

export type GetTraceRequest = {
  /**
   * The invocation's key — the value sent as its Idempotency-Key, or the one the server returned in that header when it was omitted.
   *
   * @remarks
   */
  invocationKey: string;
  /**
   * Whether to include what each span was given and produced. `true`, the default, returns `input` and `output` and the fields that describe them. `false` returns the same spans without them — everything the span recorded about itself: `id`, `parent_id`, `type`, `name`, `status`, `started_at`, `ended_at` and `usage` — which is the cheap way to read an invocation's shape, and it lets `limit` go up to 500. `after` carries the mode it was made with, so page with the same `payloads` you started with and expect a `400` otherwise.
   *
   * @remarks
   */
  payloads?: boolean | undefined;
  /**
   * Which attempts to return spans for. `final`, the default, returns only the spans of the latest attempt — the one that produced the invocation's outcome, or the one still in flight; `all` also returns the spans of the attempts before it, each marked `superseded`. Either way `attempts` in the response lists every attempt that ran.
   *
   * @remarks
   */
  attempts?: Attempts | undefined;
  /**
   * Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.
   *
   * @remarks
   */
  after?: string | undefined;
  /**
   * Maximum number of spans to return. With payloads at most 25, which is also the default; with `payloads=false` at most 500, and 500 by default, so one request usually returns a whole trace. A `limit` above the bound for the mode you asked for is a `400`. A page can be shorter, so page while `next_cursor` is present.
   *
   * @remarks
   */
  limit?: number | undefined;
};

export type GetTraceResponse = {
  headers: { [k: string]: Array<string> };
  result: models.TraceResponse;
};

/** @internal */
export const Attempts$outboundSchema: z.ZodMiniEnum<typeof Attempts> = z.enum(
  Attempts,
);

/** @internal */
export type GetTraceRequest$Outbound = {
  invocation_key: string;
  payloads: boolean;
  attempts: string;
  after?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export const GetTraceRequest$outboundSchema: z.ZodMiniType<
  GetTraceRequest$Outbound,
  GetTraceRequest
> = z.pipe(
  z.object({
    invocationKey: z.string(),
    payloads: z._default(z.boolean(), true),
    attempts: z._default(Attempts$outboundSchema, "final"),
    after: z.optional(z.string()),
    limit: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      invocationKey: "invocation_key",
    });
  }),
);

export function getTraceRequestToJSON(
  getTraceRequest: GetTraceRequest,
): string {
  return JSON.stringify(GetTraceRequest$outboundSchema.parse(getTraceRequest));
}

/** @internal */
export const GetTraceResponse$inboundSchema: z.ZodMiniType<
  GetTraceResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.TraceResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getTraceResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetTraceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTraceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTraceResponse' from JSON`,
  );
}
