/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetSpendRequest = {
  /**
   * Include usage from the UTC day containing this time onward. Defaults to 31 days before `until`.
   *
   * @remarks
   */
  since?: Date | undefined;
  /**
   * Include usage through the end of the UTC day containing this time. Defaults to now and must be after `since`.
   *
   * @remarks
   */
  until?: Date | undefined;
};

/** @internal */
export type GetSpendRequest$Outbound = {
  since?: string | undefined;
  until?: string | undefined;
};

/** @internal */
export const GetSpendRequest$outboundSchema: z.ZodMiniType<
  GetSpendRequest$Outbound,
  GetSpendRequest
> = z.object({
  since: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  until: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
});

export function getSpendRequestToJSON(
  getSpendRequest: GetSpendRequest,
): string {
  return JSON.stringify(GetSpendRequest$outboundSchema.parse(getSpendRequest));
}
