/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetTokenGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type GetTokenRequest = {
  /**
   * The token's lookup ID (the identifier portion of the token string).
   */
  id: string;
};

/** @internal */
export type GetTokenRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetTokenRequest$outboundSchema: z.ZodMiniType<
  GetTokenRequest$Outbound,
  GetTokenRequest
> = z.object({
  id: z.string(),
});

export function getTokenRequestToJSON(
  getTokenRequest: GetTokenRequest,
): string {
  return JSON.stringify(GetTokenRequest$outboundSchema.parse(getTokenRequest));
}
