/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetSessionAuditGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type GetSessionAuditRequest = {
  /**
   * Client-provided session identifier. Use the same value across requests to continue the same agent session.
   */
  id: string;
  /**
   * Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.
   *
   * @remarks
   */
  after?: string | undefined;
  /**
   * Maximum number of items to return.
   */
  limit?: number | undefined;
};

/** @internal */
export type GetSessionAuditRequest$Outbound = {
  id: string;
  after?: string | undefined;
  limit: number;
};

/** @internal */
export const GetSessionAuditRequest$outboundSchema: z.ZodMiniType<
  GetSessionAuditRequest$Outbound,
  GetSessionAuditRequest
> = z.object({
  id: z.string(),
  after: z.optional(z.string()),
  limit: z._default(z.int(), 100),
});

export function getSessionAuditRequestToJSON(
  getSessionAuditRequest: GetSessionAuditRequest,
): string {
  return JSON.stringify(
    GetSessionAuditRequest$outboundSchema.parse(getSessionAuditRequest),
  );
}
