/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetSecretGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type GetSecretRequest = {
  name: string;
};

/** @internal */
export type GetSecretRequest$Outbound = {
  name: string;
};

/** @internal */
export const GetSecretRequest$outboundSchema: z.ZodMiniType<
  GetSecretRequest$Outbound,
  GetSecretRequest
> = z.object({
  name: z.string(),
});

export function getSecretRequestToJSON(
  getSecretRequest: GetSecretRequest,
): string {
  return JSON.stringify(
    GetSecretRequest$outboundSchema.parse(getSecretRequest),
  );
}
