/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetAgentRequest = {
  /**
   * The agent's name.
   */
  name: string;
};

/** @internal */
export type GetAgentRequest$Outbound = {
  name: string;
};

/** @internal */
export const GetAgentRequest$outboundSchema: z.ZodMiniType<
  GetAgentRequest$Outbound,
  GetAgentRequest
> = z.object({
  name: z.string(),
});

export function getAgentRequestToJSON(
  getAgentRequest: GetAgentRequest,
): string {
  return JSON.stringify(GetAgentRequest$outboundSchema.parse(getAgentRequest));
}
