/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Attempts whose spans to return. `final` returns only the latest; `all` includes earlier spans marked `superseded`.
 *
 * @remarks
 */
export const Attempts = {
  Final: "final",
  All: "all",
} as const;
/**
 * Attempts whose spans to return. `final` returns only the latest; `all` includes earlier spans marked `superseded`.
 *
 * @remarks
 */
export type Attempts = ClosedEnum<typeof Attempts>;

export type GetTraceRequest = {
  /**
   * Invocation key sent or returned in the `Idempotency-Key` header.
   *
   * @remarks
   */
  invocationKey: string;
  /**
   * Whether to include span inputs and outputs. Disabling payloads raises the maximum `limit` to 500. Use the same value on every page.
   *
   * @remarks
   */
  payloads?: boolean | undefined;
  /**
   * Attempts whose spans to return. `final` returns only the latest; `all` includes earlier spans marked `superseded`.
   *
   * @remarks
   */
  attempts?: Attempts | undefined;
  /**
   * Continue after this cursor. For list responses, pass the preceding page's `next_cursor`; for session messages, pass the preceding page's last message `cursor`.
   *
   * @remarks
   */
  after?: string | undefined;
  /**
   * Maximum spans to return. Defaults to 25 with payloads and 500 without; these are also the respective maximums.
   *
   * @remarks
   */
  limit?: number | undefined;
};

export type GetTraceResponse = {
  headers: { [k: string]: Array<string> };
  result: models.TraceResponse;
};

/** @internal */
export const Attempts$outboundSchema: z.ZodMiniEnum<typeof Attempts> = z.enum(
  Attempts,
);

/** @internal */
export type GetTraceRequest$Outbound = {
  invocation_key: string;
  payloads: boolean;
  attempts: string;
  after?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export const GetTraceRequest$outboundSchema: z.ZodMiniType<
  GetTraceRequest$Outbound,
  GetTraceRequest
> = z.pipe(
  z.object({
    invocationKey: z.string(),
    payloads: z._default(z.boolean(), true),
    attempts: z._default(Attempts$outboundSchema, "final"),
    after: z.optional(z.string()),
    limit: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      invocationKey: "invocation_key",
    });
  }),
);

export function getTraceRequestToJSON(
  getTraceRequest: GetTraceRequest,
): string {
  return JSON.stringify(GetTraceRequest$outboundSchema.parse(getTraceRequest));
}

/** @internal */
export const GetTraceResponse$inboundSchema: z.ZodMiniType<
  GetTraceResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.TraceResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getTraceResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetTraceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTraceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTraceResponse' from JSON`,
  );
}
