/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetOrganizationGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type GetOrganizationRequest = {};

/** @internal */
export type GetOrganizationRequest$Outbound = {};

/** @internal */
export const GetOrganizationRequest$outboundSchema: z.ZodMiniType<
  GetOrganizationRequest$Outbound,
  GetOrganizationRequest
> = z.object({});

export function getOrganizationRequestToJSON(
  getOrganizationRequest: GetOrganizationRequest,
): string {
  return JSON.stringify(
    GetOrganizationRequest$outboundSchema.parse(getOrganizationRequest),
  );
}
