/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetSecretRequest = {
  name: string;
};

/** @internal */
export type GetSecretRequest$Outbound = {
  name: string;
};

/** @internal */
export const GetSecretRequest$outboundSchema: z.ZodMiniType<
  GetSecretRequest$Outbound,
  GetSecretRequest
> = z.object({
  name: z.string(),
});

export function getSecretRequestToJSON(
  getSecretRequest: GetSecretRequest,
): string {
  return JSON.stringify(
    GetSecretRequest$outboundSchema.parse(getSecretRequest),
  );
}
