/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetAgentRevisionGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type GetAgentRevisionRequest = {
  /**
   * The agent's name.
   */
  name: string;
  /**
   * The agent revision to fetch.
   */
  revision: string;
};

/** @internal */
export type GetAgentRevisionRequest$Outbound = {
  name: string;
  revision: string;
};

/** @internal */
export const GetAgentRevisionRequest$outboundSchema: z.ZodMiniType<
  GetAgentRevisionRequest$Outbound,
  GetAgentRevisionRequest
> = z.object({
  name: z.string(),
  revision: z.string(),
});

export function getAgentRevisionRequestToJSON(
  getAgentRevisionRequest: GetAgentRevisionRequest,
): string {
  return JSON.stringify(
    GetAgentRevisionRequest$outboundSchema.parse(getAgentRevisionRequest),
  );
}
