/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetCreditBalanceGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type GetCreditBalanceRequest = {};

/** @internal */
export type GetCreditBalanceRequest$Outbound = {};

/** @internal */
export const GetCreditBalanceRequest$outboundSchema: z.ZodMiniType<
  GetCreditBalanceRequest$Outbound,
  GetCreditBalanceRequest
> = z.object({});

export function getCreditBalanceRequestToJSON(
  getCreditBalanceRequest: GetCreditBalanceRequest,
): string {
  return JSON.stringify(
    GetCreditBalanceRequest$outboundSchema.parse(getCreditBalanceRequest),
  );
}
