/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetSessionAuditRequest = {
  /**
   * Client-provided session identifier. Reuse it to continue the session.
   *
   * @remarks
   */
  id: string;
  /**
   * Continue after this cursor. For list responses, pass the preceding page's `next_cursor`; for session messages, pass the preceding page's last message `cursor`.
   *
   * @remarks
   */
  after?: string | undefined;
  /**
   * Maximum number of items to return.
   */
  limit?: number | undefined;
};

/** @internal */
export type GetSessionAuditRequest$Outbound = {
  id: string;
  after?: string | undefined;
  limit: number;
};

/** @internal */
export const GetSessionAuditRequest$outboundSchema: z.ZodMiniType<
  GetSessionAuditRequest$Outbound,
  GetSessionAuditRequest
> = z.object({
  id: z.string(),
  after: z.optional(z.string()),
  limit: z._default(z.int(), 100),
});

export function getSessionAuditRequestToJSON(
  getSessionAuditRequest: GetSessionAuditRequest,
): string {
  return JSON.stringify(
    GetSessionAuditRequest$outboundSchema.parse(getSessionAuditRequest),
  );
}
