/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetAgentGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type GetAgentRequest = {
  /**
   * The agent's name.
   */
  name: string;
};

/** @internal */
export type GetAgentRequest$Outbound = {
  name: string;
};

/** @internal */
export const GetAgentRequest$outboundSchema: z.ZodMiniType<
  GetAgentRequest$Outbound,
  GetAgentRequest
> = z.object({
  name: z.string(),
});

export function getAgentRequestToJSON(
  getAgentRequest: GetAgentRequest,
): string {
  return JSON.stringify(GetAgentRequest$outboundSchema.parse(getAgentRequest));
}
