/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ListTracesGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type ListTracesRequest = {
  /**
   * Return only invocations of this agent (e.g. "support-triage"). Invocations with no recorded agent name are not matched.
   *
   * @remarks
   */
  agentName?: string | undefined;
  /**
   * Return only invocations of this exact agent revision (e.g. "a1b2c3d4"). Combines with `agent_name`. Invocations with no recorded revision are not matched.
   *
   * @remarks
   */
  agentRevision?: string | undefined;
  /**
   * Return only invocations with this outcome. An invocation whose spans have aged out is still matched by the outcome it recorded.
   *
   * @remarks
   */
  status?: models.TraceStatus | undefined;
  /**
   * Return only invocations of this session — the session identifier you ran it with. A session you do not have is a `404`.
   *
   * @remarks
   */
  sessionId?: string | undefined;
  /**
   * Return only invocations that started at or after this time. Defaults to 31 days ago; pass it to search further back.
   *
   * @remarks
   */
  since?: Date | undefined;
  /**
   * Return only invocations that started at or before this time. Defaults to now, and must be after `since`; an earlier `until` is a `400`.
   *
   * @remarks
   */
  until?: Date | undefined;
  /**
   * Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.
   *
   * @remarks
   */
  after?: string | undefined;
  /**
   * Maximum number of traces to return. A page can be shorter, so page while `next_cursor` is present.
   *
   * @remarks
   */
  limit?: number | undefined;
};

/** @internal */
export type ListTracesRequest$Outbound = {
  agent_name?: string | undefined;
  agent_revision?: string | undefined;
  status?: string | undefined;
  session_id?: string | undefined;
  since?: string | undefined;
  until?: string | undefined;
  after?: string | undefined;
  limit: number;
};

/** @internal */
export const ListTracesRequest$outboundSchema: z.ZodMiniType<
  ListTracesRequest$Outbound,
  ListTracesRequest
> = z.pipe(
  z.object({
    agentName: z.optional(z.string()),
    agentRevision: z.optional(z.string()),
    status: z.optional(models.TraceStatus$outboundSchema),
    sessionId: z.optional(z.string()),
    since: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    until: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    after: z.optional(z.string()),
    limit: z._default(z.int(), 10),
  }),
  z.transform((v) => {
    return remap$(v, {
      agentName: "agent_name",
      agentRevision: "agent_revision",
      sessionId: "session_id",
    });
  }),
);

export function listTracesRequestToJSON(
  listTracesRequest: ListTracesRequest,
): string {
  return JSON.stringify(
    ListTracesRequest$outboundSchema.parse(listTracesRequest),
  );
}
