/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ListSessionsGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type ListSessionsRequest = {
  /**
   * Return only sessions that ran this agent (e.g. "support-triage").
   *
   * @remarks
   */
  agentName?: string | undefined;
  /**
   * Return only sessions that ran this exact agent revision (e.g. "a1b2c3d4"). Requires `agent_name`; a revision without an agent name is a `400`.
   *
   * @remarks
   */
  agentRevision?: string | undefined;
  /**
   * Return only sessions with an invocation that ended this way, or is `RUNNING` now. `DONE` matches a successful invocation.
   *
   * @remarks
   */
  status?: models.SessionState | undefined;
  /**
   * Return only the session that ran this invocation, whether it is still running or has ended.
   *
   * @remarks
   */
  invocationKey?: string | undefined;
  /**
   * Return only sessions with an invocation that started at or after this time. Without `since` or `until`, the listing covers sessions used in the last 31 days; pass it to search further back.
   *
   * @remarks
   */
  since?: Date | undefined;
  /**
   * Return only sessions with an invocation that started at or before this time. Defaults to now, and must be after `since`; an earlier `until` is a `400`.
   *
   * @remarks
   */
  until?: Date | undefined;
  /**
   * Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.
   *
   * @remarks
   */
  after?: string | undefined;
  /**
   * Maximum number of sessions to return. A page can be shorter, so page while `next_cursor` is present.
   *
   * @remarks
   */
  limit?: number | undefined;
};

/** @internal */
export type ListSessionsRequest$Outbound = {
  agent_name?: string | undefined;
  agent_revision?: string | undefined;
  status?: string | undefined;
  invocation_key?: string | undefined;
  since?: string | undefined;
  until?: string | undefined;
  after?: string | undefined;
  limit: number;
};

/** @internal */
export const ListSessionsRequest$outboundSchema: z.ZodMiniType<
  ListSessionsRequest$Outbound,
  ListSessionsRequest
> = z.pipe(
  z.object({
    agentName: z.optional(z.string()),
    agentRevision: z.optional(z.string()),
    status: z.optional(models.SessionState$outboundSchema),
    invocationKey: z.optional(z.string()),
    since: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    until: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    after: z.optional(z.string()),
    limit: z._default(z.int(), 25),
  }),
  z.transform((v) => {
    return remap$(v, {
      agentName: "agent_name",
      agentRevision: "agent_revision",
      invocationKey: "invocation_key",
    });
  }),
);

export function listSessionsRequestToJSON(
  listSessionsRequest: ListSessionsRequest,
): string {
  return JSON.stringify(
    ListSessionsRequest$outboundSchema.parse(listSessionsRequest),
  );
}
