/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListOrganizationMembersGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type ListOrganizationMembersRequest = {};

/** @internal */
export type ListOrganizationMembersRequest$Outbound = {};

/** @internal */
export const ListOrganizationMembersRequest$outboundSchema: z.ZodMiniType<
  ListOrganizationMembersRequest$Outbound,
  ListOrganizationMembersRequest
> = z.object({});

export function listOrganizationMembersRequestToJSON(
  listOrganizationMembersRequest: ListOrganizationMembersRequest,
): string {
  return JSON.stringify(
    ListOrganizationMembersRequest$outboundSchema.parse(
      listOrganizationMembersRequest,
    ),
  );
}
