/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListModelsGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type ListModelsRequest = {};

/** @internal */
export type ListModelsRequest$Outbound = {};

/** @internal */
export const ListModelsRequest$outboundSchema: z.ZodMiniType<
  ListModelsRequest$Outbound,
  ListModelsRequest
> = z.object({});

export function listModelsRequestToJSON(
  listModelsRequest: ListModelsRequest,
): string {
  return JSON.stringify(
    ListModelsRequest$outboundSchema.parse(listModelsRequest),
  );
}
