/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListInvitesGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type ListInvitesRequest = {};

/** @internal */
export type ListInvitesRequest$Outbound = {};

/** @internal */
export const ListInvitesRequest$outboundSchema: z.ZodMiniType<
  ListInvitesRequest$Outbound,
  ListInvitesRequest
> = z.object({});

export function listInvitesRequestToJSON(
  listInvitesRequest: ListInvitesRequest,
): string {
  return JSON.stringify(
    ListInvitesRequest$outboundSchema.parse(listInvitesRequest),
  );
}
