/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ListTracesRequest = {
  /**
   * Return only invocations of this agent (e.g. "support-triage").
   *
   * @remarks
   */
  agentName?: string | undefined;
  /**
   * Return only invocations of this agent revision (e.g. "a1b2c3d4"). Combines with `agent_name`.
   *
   * @remarks
   */
  agentRevision?: string | undefined;
  /**
   * Return only invocations with this status.
   *
   * @remarks
   */
  status?: models.TraceStatus | undefined;
  /**
   * Return only invocations in this session. An unknown session returns `404`.
   *
   * @remarks
   */
  sessionId?: string | undefined;
  /**
   * Return only invocations that started at or after this time. Defaults to 31 days ago.
   *
   * @remarks
   */
  since?: Date | undefined;
  /**
   * Return only invocations that started at or before this time. Defaults to now and must be after `since`.
   *
   * @remarks
   */
  until?: Date | undefined;
  /**
   * Continue after this cursor. For list responses, pass the preceding page's `next_cursor`; for session messages, pass the preceding page's last message `cursor`.
   *
   * @remarks
   */
  after?: string | undefined;
  /**
   * Maximum number of traces to return.
   */
  limit?: number | undefined;
};

/** @internal */
export type ListTracesRequest$Outbound = {
  agent_name?: string | undefined;
  agent_revision?: string | undefined;
  status?: string | undefined;
  session_id?: string | undefined;
  since?: string | undefined;
  until?: string | undefined;
  after?: string | undefined;
  limit: number;
};

/** @internal */
export const ListTracesRequest$outboundSchema: z.ZodMiniType<
  ListTracesRequest$Outbound,
  ListTracesRequest
> = z.pipe(
  z.object({
    agentName: z.optional(z.string()),
    agentRevision: z.optional(z.string()),
    status: z.optional(models.TraceStatus$outboundSchema),
    sessionId: z.optional(z.string()),
    since: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    until: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    after: z.optional(z.string()),
    limit: z._default(z.int(), 10),
  }),
  z.transform((v) => {
    return remap$(v, {
      agentName: "agent_name",
      agentRevision: "agent_revision",
      sessionId: "session_id",
    });
  }),
);

export function listTracesRequestToJSON(
  listTracesRequest: ListTracesRequest,
): string {
  return JSON.stringify(
    ListTracesRequest$outboundSchema.parse(listTracesRequest),
  );
}
