/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListAgentsRequest = {
  /**
   * Return only the agent with this exact name.
   */
  name?: string | undefined;
};

/** @internal */
export type ListAgentsRequest$Outbound = {
  name?: string | undefined;
};

/** @internal */
export const ListAgentsRequest$outboundSchema: z.ZodMiniType<
  ListAgentsRequest$Outbound,
  ListAgentsRequest
> = z.object({
  name: z.optional(z.string()),
});

export function listAgentsRequestToJSON(
  listAgentsRequest: ListAgentsRequest,
): string {
  return JSON.stringify(
    ListAgentsRequest$outboundSchema.parse(listAgentsRequest),
  );
}
