/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListMemoryGroupsRequest = {
  /**
   * Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.
   *
   * @remarks
   */
  after?: string | undefined;
  /**
   * Maximum number of items to return.
   */
  limit?: number | undefined;
};

/** @internal */
export type ListMemoryGroupsRequest$Outbound = {
  after?: string | undefined;
  limit: number;
};

/** @internal */
export const ListMemoryGroupsRequest$outboundSchema: z.ZodMiniType<
  ListMemoryGroupsRequest$Outbound,
  ListMemoryGroupsRequest
> = z.object({
  after: z.optional(z.string()),
  limit: z._default(z.int(), 100),
});

export function listMemoryGroupsRequestToJSON(
  listMemoryGroupsRequest: ListMemoryGroupsRequest,
): string {
  return JSON.stringify(
    ListMemoryGroupsRequest$outboundSchema.parse(listMemoryGroupsRequest),
  );
}
