/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListCreditLedgerGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type ListCreditLedgerRequest = {
  /**
   * Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.
   *
   * @remarks
   */
  after?: string | undefined;
  /**
   * Maximum number of items to return.
   */
  limit?: number | undefined;
};

/** @internal */
export type ListCreditLedgerRequest$Outbound = {
  after?: string | undefined;
  limit: number;
};

/** @internal */
export const ListCreditLedgerRequest$outboundSchema: z.ZodMiniType<
  ListCreditLedgerRequest$Outbound,
  ListCreditLedgerRequest
> = z.object({
  after: z.optional(z.string()),
  limit: z._default(z.int(), 100),
});

export function listCreditLedgerRequestToJSON(
  listCreditLedgerRequest: ListCreditLedgerRequest,
): string {
  return JSON.stringify(
    ListCreditLedgerRequest$outboundSchema.parse(listCreditLedgerRequest),
  );
}
