/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListSecretsGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type ListSecretsRequest = {};

/** @internal */
export type ListSecretsRequest$Outbound = {};

/** @internal */
export const ListSecretsRequest$outboundSchema: z.ZodMiniType<
  ListSecretsRequest$Outbound,
  ListSecretsRequest
> = z.object({});

export function listSecretsRequestToJSON(
  listSecretsRequest: ListSecretsRequest,
): string {
  return JSON.stringify(
    ListSecretsRequest$outboundSchema.parse(listSecretsRequest),
  );
}
