/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListAgentsGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type ListAgentsRequest = {};

/** @internal */
export type ListAgentsRequest$Outbound = {};

/** @internal */
export const ListAgentsRequest$outboundSchema: z.ZodMiniType<
  ListAgentsRequest$Outbound,
  ListAgentsRequest
> = z.object({});

export function listAgentsRequestToJSON(
  listAgentsRequest: ListAgentsRequest,
): string {
  return JSON.stringify(
    ListAgentsRequest$outboundSchema.parse(listAgentsRequest),
  );
}
