/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListTokensGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type ListTokensRequest = {};

/** @internal */
export type ListTokensRequest$Outbound = {};

/** @internal */
export const ListTokensRequest$outboundSchema: z.ZodMiniType<
  ListTokensRequest$Outbound,
  ListTokensRequest
> = z.object({});

export function listTokensRequestToJSON(
  listTokensRequest: ListTokensRequest,
): string {
  return JSON.stringify(
    ListTokensRequest$outboundSchema.parse(listTokensRequest),
  );
}
