/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ListSessionsRequest = {
  /**
   * Return only sessions that ran this agent (e.g. "support-triage").
   *
   * @remarks
   */
  agentName?: string | undefined;
  /**
   * Return only sessions that ran this agent revision (e.g. "a1b2c3d4"). Requires `agent_name`.
   *
   * @remarks
   */
  agentRevision?: string | undefined;
  /**
   * Return only sessions with an invocation in this state. `DONE` matches a successful invocation.
   *
   * @remarks
   */
  status?: models.SessionState | undefined;
  /**
   * Return only the session containing this invocation.
   *
   * @remarks
   */
  invocationKey?: string | undefined;
  /**
   * Return only sessions with an invocation that started at or after this time. Defaults to 31 days ago.
   *
   * @remarks
   */
  since?: Date | undefined;
  /**
   * Return only sessions with an invocation that started at or before this time. Defaults to now and must be after `since`.
   *
   * @remarks
   */
  until?: Date | undefined;
  /**
   * Continue after this cursor. For list responses, pass the preceding page's `next_cursor`; for session messages, pass the preceding page's last message `cursor`.
   *
   * @remarks
   */
  after?: string | undefined;
  /**
   * Maximum number of sessions to return.
   */
  limit?: number | undefined;
};

/** @internal */
export type ListSessionsRequest$Outbound = {
  agent_name?: string | undefined;
  agent_revision?: string | undefined;
  status?: string | undefined;
  invocation_key?: string | undefined;
  since?: string | undefined;
  until?: string | undefined;
  after?: string | undefined;
  limit: number;
};

/** @internal */
export const ListSessionsRequest$outboundSchema: z.ZodMiniType<
  ListSessionsRequest$Outbound,
  ListSessionsRequest
> = z.pipe(
  z.object({
    agentName: z.optional(z.string()),
    agentRevision: z.optional(z.string()),
    status: z.optional(models.SessionState$outboundSchema),
    invocationKey: z.optional(z.string()),
    since: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    until: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    after: z.optional(z.string()),
    limit: z._default(z.int(), 25),
  }),
  z.transform((v) => {
    return remap$(v, {
      agentName: "agent_name",
      agentRevision: "agent_revision",
      invocationKey: "invocation_key",
    });
  }),
);

export function listSessionsRequestToJSON(
  listSessionsRequest: ListSessionsRequest,
): string {
  return JSON.stringify(
    ListSessionsRequest$outboundSchema.parse(listSessionsRequest),
  );
}
