/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListMemoriesRequest = {
  /**
   * Memory group to read or delete, matching the agent's `memory.group`.
   *
   * @remarks
   */
  group: string;
  /**
   * Continue after this cursor. For list responses, pass the preceding page's `next_cursor`; for session messages, pass the preceding page's last message `cursor`.
   *
   * @remarks
   */
  after?: string | undefined;
  /**
   * Maximum number of items to return.
   */
  limit?: number | undefined;
};

/** @internal */
export type ListMemoriesRequest$Outbound = {
  group: string;
  after?: string | undefined;
  limit: number;
};

/** @internal */
export const ListMemoriesRequest$outboundSchema: z.ZodMiniType<
  ListMemoriesRequest$Outbound,
  ListMemoriesRequest
> = z.object({
  group: z.string(),
  after: z.optional(z.string()),
  limit: z._default(z.int(), 100),
});

export function listMemoriesRequestToJSON(
  listMemoriesRequest: ListMemoriesRequest,
): string {
  return JSON.stringify(
    ListMemoriesRequest$outboundSchema.parse(listMemoriesRequest),
  );
}
