/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListMemoriesGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type ListMemoriesRequest = {
  /**
   * The memory group to read or delete — the `memory.group` value the agents sharing those memories run with.
   *
   * @remarks
   */
  group: string;
  /**
   * Opaque pagination cursor. Return only items positioned after it; pass a value obtained from a previous page to fetch the next one.
   *
   * @remarks
   */
  after?: string | undefined;
  /**
   * Maximum number of items to return.
   */
  limit?: number | undefined;
};

/** @internal */
export type ListMemoriesRequest$Outbound = {
  group: string;
  after?: string | undefined;
  limit: number;
};

/** @internal */
export const ListMemoriesRequest$outboundSchema: z.ZodMiniType<
  ListMemoriesRequest$Outbound,
  ListMemoriesRequest
> = z.object({
  group: z.string(),
  after: z.optional(z.string()),
  limit: z._default(z.int(), 100),
});

export function listMemoriesRequestToJSON(
  listMemoriesRequest: ListMemoriesRequest,
): string {
  return JSON.stringify(
    ListMemoriesRequest$outboundSchema.parse(listMemoriesRequest),
  );
}
