/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type RemoveOrganizationMemberRequest = {
  /**
   * The member's user identifier.
   */
  userId: string;
};

/** @internal */
export type RemoveOrganizationMemberRequest$Outbound = {
  user_id: string;
};

/** @internal */
export const RemoveOrganizationMemberRequest$outboundSchema: z.ZodMiniType<
  RemoveOrganizationMemberRequest$Outbound,
  RemoveOrganizationMemberRequest
> = z.pipe(
  z.object({
    userId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      userId: "user_id",
    });
  }),
);

export function removeOrganizationMemberRequestToJSON(
  removeOrganizationMemberRequest: RemoveOrganizationMemberRequest,
): string {
  return JSON.stringify(
    RemoveOrganizationMemberRequest$outboundSchema.parse(
      removeOrganizationMemberRequest,
    ),
  );
}
