/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type RevokeInviteGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type RevokeInviteRequest = {
  /**
   * The invitation identifier.
   */
  id: string;
};

/** @internal */
export type RevokeInviteRequest$Outbound = {
  id: string;
};

/** @internal */
export const RevokeInviteRequest$outboundSchema: z.ZodMiniType<
  RevokeInviteRequest$Outbound,
  RevokeInviteRequest
> = z.object({
  id: z.string(),
});

export function revokeInviteRequestToJSON(
  revokeInviteRequest: RevokeInviteRequest,
): string {
  return JSON.stringify(
    RevokeInviteRequest$outboundSchema.parse(revokeInviteRequest),
  );
}
