/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type RevokeInviteRequest = {
  /**
   * The invitation identifier.
   */
  id: string;
};

/** @internal */
export type RevokeInviteRequest$Outbound = {
  id: string;
};

/** @internal */
export const RevokeInviteRequest$outboundSchema: z.ZodMiniType<
  RevokeInviteRequest$Outbound,
  RevokeInviteRequest
> = z.object({
  id: z.string(),
});

export function revokeInviteRequestToJSON(
  revokeInviteRequest: RevokeInviteRequest,
): string {
  return JSON.stringify(
    RevokeInviteRequest$outboundSchema.parse(revokeInviteRequest),
  );
}
