/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type RunSessionRequest = {
  /**
   * Client-provided session identifier. Use the same value across requests to continue the same agent session.
   */
  id: string;
  /**
   * Optional but strongly encouraged. Uniquely identifies this invocation of the session; reuse the same value to safely retry a request, and a new value starts a new invocation. When omitted, the server generates a key for the invocation and returns it in the Idempotency-Key response header, but the request is not retry-safe.
   *
   * @remarks
   */
  idempotencyKey?: string | undefined;
  /**
   * Wait up to this many seconds for the assistant response. Omit to return after the invocation is accepted; use 0 to wait until a response is available.
   *
   * @remarks
   */
  waitTimeoutSeconds?: number | undefined;
  body: models.RunSessionRequest;
};

export type RunSessionResponse = {
  headers: { [k: string]: Array<string> };
  result: models.SessionResponse;
};

/** @internal */
export type RunSessionRequest$Outbound = {
  id: string;
  "Idempotency-Key"?: string | undefined;
  wait_timeout_seconds?: number | undefined;
  body: models.RunSessionRequest$Outbound;
};

/** @internal */
export const RunSessionRequest$outboundSchema: z.ZodMiniType<
  RunSessionRequest$Outbound,
  RunSessionRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.optional(z.string()),
    waitTimeoutSeconds: z.optional(z.int()),
    body: models.RunSessionRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
      waitTimeoutSeconds: "wait_timeout_seconds",
    });
  }),
);

export function runSessionRequestToJSON(
  runSessionRequest: RunSessionRequest,
): string {
  return JSON.stringify(
    RunSessionRequest$outboundSchema.parse(runSessionRequest),
  );
}

/** @internal */
export const RunSessionResponse$inboundSchema: z.ZodMiniType<
  RunSessionResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.SessionResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function runSessionResponseFromJSON(
  jsonString: string,
): SafeParseResult<RunSessionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RunSessionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RunSessionResponse' from JSON`,
  );
}
