/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type SetOrganizationMemberRoleRequest = {
  /**
   * The member's user identifier.
   */
  userId: string;
  body: models.SetOrganizationMemberRoleRequest;
};

/** @internal */
export type SetOrganizationMemberRoleRequest$Outbound = {
  user_id: string;
  body: models.SetOrganizationMemberRoleRequest$Outbound;
};

/** @internal */
export const SetOrganizationMemberRoleRequest$outboundSchema: z.ZodMiniType<
  SetOrganizationMemberRoleRequest$Outbound,
  SetOrganizationMemberRoleRequest
> = z.pipe(
  z.object({
    userId: z.string(),
    body: models.SetOrganizationMemberRoleRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      userId: "user_id",
    });
  }),
);

export function setOrganizationMemberRoleRequestToJSON(
  setOrganizationMemberRoleRequest: SetOrganizationMemberRoleRequest,
): string {
  return JSON.stringify(
    SetOrganizationMemberRoleRequest$outboundSchema.parse(
      setOrganizationMemberRoleRequest,
    ),
  );
}
