/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateSecretGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type UpdateSecretRequest = {
  name: string;
  body: models.UpdateSecretRequest;
};

/** @internal */
export type UpdateSecretRequest$Outbound = {
  name: string;
  body: models.UpdateSecretRequest$Outbound;
};

/** @internal */
export const UpdateSecretRequest$outboundSchema: z.ZodMiniType<
  UpdateSecretRequest$Outbound,
  UpdateSecretRequest
> = z.object({
  name: z.string(),
  body: models.UpdateSecretRequest$outboundSchema,
});

export function updateSecretRequestToJSON(
  updateSecretRequest: UpdateSecretRequest,
): string {
  return JSON.stringify(
    UpdateSecretRequest$outboundSchema.parse(updateSecretRequest),
  );
}
