/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type WhoamiGlobals = {
  /**
   * The id of the organization the request acts on, which must be one the caller belongs to. Defaults to the organization the caller joined first. Ignored for API keys, which are bound to one organization.
   *
   * @remarks
   */
  xAlbusOrganization?: string | undefined;
};

export type WhoamiRequest = {};

/** @internal */
export type WhoamiRequest$Outbound = {};

/** @internal */
export const WhoamiRequest$outboundSchema: z.ZodMiniType<
  WhoamiRequest$Outbound,
  WhoamiRequest
> = z.object({});

export function whoamiRequestToJSON(whoamiRequest: WhoamiRequest): string {
  return JSON.stringify(WhoamiRequest$outboundSchema.parse(whoamiRequest));
}
