/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MCPServer,
  MCPServer$inboundSchema,
  MCPServer$Outbound,
  MCPServer$outboundSchema,
} from "./mcp-server.js";
import {
  MemoryConfig,
  MemoryConfig$inboundSchema,
  MemoryConfig$Outbound,
  MemoryConfig$outboundSchema,
} from "./memory-config.js";
import {
  Model,
  Model$inboundSchema,
  Model$Outbound,
  Model$outboundSchema,
} from "./model.js";
import {
  Tools,
  Tools$inboundSchema,
  Tools$Outbound,
  Tools$outboundSchema,
} from "./tools.js";

/**
 * The agent configuration for an invocation: the model, tools, instructions, and MCP servers that define its behavior. Invocations with the same configuration share a revision.
 *
 * @remarks
 */
export type AgentConfig = {
  model: Model;
  /**
   * The built-in tools the model may call. Include a tool's block to offer it (e.g. {"web_search": {}}); omit it to withhold it.
   *
   * @remarks
   */
  tools?: Tools | undefined;
  /**
   * Configures durable memory shared by invocations in the same group.
   *
   * @remarks
   */
  memory?: MemoryConfig | undefined;
  /**
   * System instructions for the model. Uses a default if omitted.
   */
  systemPrompt?: string | undefined;
  /**
   * Max model steps before the invocation stops. Uses a default if omitted.
   *
   * @remarks
   */
  maxSteps?: number | undefined;
  /**
   * MCP servers whose tools are offered to the model.
   */
  mcpServers?: Array<MCPServer> | undefined;
  /**
   * JSON Schema the answer must conform to; the answer is returned as a JSON document. Every object in the schema must set "additionalProperties" to false and list every property in "required". Choose a model that supports structured output.
   *
   * @remarks
   */
  outputFormat?: { [k: string]: any } | undefined;
};

/** @internal */
export const AgentConfig$inboundSchema: z.ZodMiniType<AgentConfig, unknown> = z
  .pipe(
    z.object({
      model: Model$inboundSchema,
      tools: types.optional(Tools$inboundSchema),
      memory: types.optional(MemoryConfig$inboundSchema),
      system_prompt: types.optional(types.string()),
      max_steps: types.optional(types.number()),
      mcp_servers: types.optional(z.array(MCPServer$inboundSchema)),
      output_format: types.optional(z.record(z.string(), z.any())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "system_prompt": "systemPrompt",
        "max_steps": "maxSteps",
        "mcp_servers": "mcpServers",
        "output_format": "outputFormat",
      });
    }),
  );
/** @internal */
export type AgentConfig$Outbound = {
  model: Model$Outbound;
  tools?: Tools$Outbound | undefined;
  memory?: MemoryConfig$Outbound | undefined;
  system_prompt?: string | undefined;
  max_steps?: number | undefined;
  mcp_servers?: Array<MCPServer$Outbound> | undefined;
  output_format?: { [k: string]: any } | undefined;
};

/** @internal */
export const AgentConfig$outboundSchema: z.ZodMiniType<
  AgentConfig$Outbound,
  AgentConfig
> = z.pipe(
  z.object({
    model: Model$outboundSchema,
    tools: z.optional(Tools$outboundSchema),
    memory: z.optional(MemoryConfig$outboundSchema),
    systemPrompt: z.optional(z.string()),
    maxSteps: z.optional(z.int()),
    mcpServers: z.optional(z.array(MCPServer$outboundSchema)),
    outputFormat: z.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      systemPrompt: "system_prompt",
      maxSteps: "max_steps",
      mcpServers: "mcp_servers",
      outputFormat: "output_format",
    });
  }),
);

export function agentConfigToJSON(agentConfig: AgentConfig): string {
  return JSON.stringify(AgentConfig$outboundSchema.parse(agentConfig));
}
export function agentConfigFromJSON(
  jsonString: string,
): SafeParseResult<AgentConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentConfig' from JSON`,
  );
}
