/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * A reference to one agent revision, without its configuration.
 */
export type AgentRevisionMeta = {
  /**
   * Identifier of this agent revision.
   */
  revision: string;
  /**
   * When this revision first ran.
   */
  createdAt: Date;
};

/** @internal */
export const AgentRevisionMeta$inboundSchema: z.ZodMiniType<
  AgentRevisionMeta,
  unknown
> = z.pipe(
  z.object({
    revision: types.string(),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
    });
  }),
);

export function agentRevisionMetaFromJSON(
  jsonString: string,
): SafeParseResult<AgentRevisionMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentRevisionMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentRevisionMeta' from JSON`,
  );
}
