/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AgentRevisionMeta,
  AgentRevisionMeta$inboundSchema,
} from "./agent-revision-meta.js";
import {
  AgentRevision,
  AgentRevision$inboundSchema,
} from "./agent-revision.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * An agent identified by name, with its current revision's full configuration and the list of all its revisions newest first.
 *
 * @remarks
 */
export type Agent = {
  /**
   * The agent's name.
   */
  name: string;
  /**
   * One revision of an agent, with its full configuration.
   */
  current: AgentRevision;
  /**
   * All revisions of the agent, newest first.
   */
  revisions: Array<AgentRevisionMeta>;
};

/** @internal */
export const Agent$inboundSchema: z.ZodMiniType<Agent, unknown> = z.object({
  name: types.string(),
  current: AgentRevision$inboundSchema,
  revisions: z.array(AgentRevisionMeta$inboundSchema),
});

export function agentFromJSON(
  jsonString: string,
): SafeParseResult<Agent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Agent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Agent' from JSON`,
  );
}
