/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { AgentConfig, AgentConfig$inboundSchema } from "./agent-config.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * One revision of an agent, with its full configuration.
 */
export type AgentRevision = {
  /**
   * Identifier of this agent revision.
   */
  revision: string;
  /**
   * When this revision first ran.
   */
  createdAt: Date;
  /**
   * The agent configuration for a run: the model, tools, instructions, and MCP servers that define its behavior. Runs with the same configuration share a revision.
   *
   * @remarks
   */
  config: AgentConfig;
};

/** @internal */
export const AgentRevision$inboundSchema: z.ZodMiniType<
  AgentRevision,
  unknown
> = z.pipe(
  z.object({
    revision: types.string(),
    created_at: types.date(),
    config: AgentConfig$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
    });
  }),
);

export function agentRevisionFromJSON(
  jsonString: string,
): SafeParseResult<AgentRevision, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentRevision$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentRevision' from JSON`,
  );
}
