/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MCPServer,
  MCPServer$inboundSchema,
  MCPServer$Outbound,
  MCPServer$outboundSchema,
} from "./mcp-server.js";
import {
  Model,
  Model$inboundSchema,
  Model$Outbound,
  Model$outboundSchema,
} from "./model.js";

/**
 * The agent configuration for a run: the model, tools, instructions, and MCP servers that define its behavior. Runs with the same configuration share a revision.
 *
 * @remarks
 */
export type AgentConfig = {
  model: Model;
  /**
   * Names of the tools the model may call (e.g. "WEB_SEARCH").
   */
  tools?: Array<string> | undefined;
  /**
   * System instructions for the model. Uses a default if omitted.
   */
  systemPrompt?: string | undefined;
  /**
   * Max model steps before the run stops. Uses a default if omitted.
   */
  maxSteps?: number | undefined;
  /**
   * MCP servers whose tools are offered to the model.
   */
  mcpServers?: Array<MCPServer> | undefined;
};

/** @internal */
export const AgentConfig$inboundSchema: z.ZodMiniType<AgentConfig, unknown> = z
  .pipe(
    z.object({
      model: Model$inboundSchema,
      tools: types.optional(z.array(types.string())),
      system_prompt: types.optional(types.string()),
      max_steps: types.optional(types.number()),
      mcp_servers: types.optional(z.array(MCPServer$inboundSchema)),
    }),
    z.transform((v) => {
      return remap$(v, {
        "system_prompt": "systemPrompt",
        "max_steps": "maxSteps",
        "mcp_servers": "mcpServers",
      });
    }),
  );
/** @internal */
export type AgentConfig$Outbound = {
  model: Model$Outbound;
  tools?: Array<string> | undefined;
  system_prompt?: string | undefined;
  max_steps?: number | undefined;
  mcp_servers?: Array<MCPServer$Outbound> | undefined;
};

/** @internal */
export const AgentConfig$outboundSchema: z.ZodMiniType<
  AgentConfig$Outbound,
  AgentConfig
> = z.pipe(
  z.object({
    model: Model$outboundSchema,
    tools: z.optional(z.array(z.string())),
    systemPrompt: z.optional(z.string()),
    maxSteps: z.optional(z.int()),
    mcpServers: z.optional(z.array(MCPServer$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      systemPrompt: "system_prompt",
      maxSteps: "max_steps",
      mcpServers: "mcp_servers",
    });
  }),
);

export function agentConfigToJSON(agentConfig: AgentConfig): string {
  return JSON.stringify(AgentConfig$outboundSchema.parse(agentConfig));
}
export function agentConfigFromJSON(
  jsonString: string,
): SafeParseResult<AgentConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentConfig' from JSON`,
  );
}
