/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * A row in the agent list — an agent's identity and activity.
 */
export type AgentMeta = {
  /**
   * The agent's name.
   */
  name: string;
  /**
   * Number of distinct revisions of this agent.
   */
  revisionCount: number;
  /**
   * When the agent first ran.
   */
  createdAt: Date;
  /**
   * When the agent last ran.
   */
  updatedAt: Date;
};

/** @internal */
export const AgentMeta$inboundSchema: z.ZodMiniType<AgentMeta, unknown> = z
  .pipe(
    z.object({
      name: types.string(),
      revision_count: types.number(),
      created_at: types.date(),
      updated_at: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "revision_count": "revisionCount",
        "created_at": "createdAt",
        "updated_at": "updatedAt",
      });
    }),
  );

export function agentMetaFromJSON(
  jsonString: string,
): SafeParseResult<AgentMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentMeta' from JSON`,
  );
}
