/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * A short-lived identity token issued by Albus for the calling organization and invocation, sent as "Authorization: Bearer". Your server must trust the organization's issuer (the "issuer" of the Organization resource) and require the server "url" as the audience; the issuer publishes its signing keys at "<issuer>/.well-known/jwks.json".
 *
 * @remarks
 *
 * @see {@link https://docs.albus.sh/guides/mcp-server-auth}
 */
export type AlbusIdentityJWTAuth = {
  type: "albus_identity_jwt";
};

/** @internal */
export const AlbusIdentityJWTAuth$inboundSchema: z.ZodMiniType<
  AlbusIdentityJWTAuth,
  unknown
> = z.object({
  type: types.literal("albus_identity_jwt"),
});
/** @internal */
export type AlbusIdentityJWTAuth$Outbound = {
  type: "albus_identity_jwt";
};

/** @internal */
export const AlbusIdentityJWTAuth$outboundSchema: z.ZodMiniType<
  AlbusIdentityJWTAuth$Outbound,
  AlbusIdentityJWTAuth
> = z.object({
  type: z.literal("albus_identity_jwt"),
});

export function albusIdentityJWTAuthToJSON(
  albusIdentityJWTAuth: AlbusIdentityJWTAuth,
): string {
  return JSON.stringify(
    AlbusIdentityJWTAuth$outboundSchema.parse(albusIdentityJWTAuth),
  );
}
export function albusIdentityJWTAuthFromJSON(
  jsonString: string,
): SafeParseResult<AlbusIdentityJWTAuth, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AlbusIdentityJWTAuth$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AlbusIdentityJWTAuth' from JSON`,
  );
}
