/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * The kind of event (e.g. "agent_invocation" for the request that started the run, "model_call" for a model call and the tool calls it requested, "tool_call" for an executed tool call and its output). Events recorded earlier use "llm_call" and "tool_result" for those same two kinds.
 *
 * @remarks
 */
export const Type = {
  AgentInvocation: "agent_invocation",
  ModelCall: "model_call",
  ToolCall: "tool_call",
  HarnessExit: "harness_exit",
  RunFailed: "run_failed",
  RunSucceeded: "run_succeeded",
  LlmCall: "llm_call",
  ToolResult: "tool_result",
} as const;
/**
 * The kind of event (e.g. "agent_invocation" for the request that started the run, "model_call" for a model call and the tool calls it requested, "tool_call" for an executed tool call and its output). Events recorded earlier use "llm_call" and "tool_result" for those same two kinds.
 *
 * @remarks
 */
export type Type = OpenEnum<typeof Type>;

export type AuditEvent = {
  /**
   * Stable identifier of this audit event within the session.
   */
  id: string;
  /**
   * The session this event belongs to.
   */
  sessionId: string;
  /**
   * Idempotency key of the run during which this event occurred.
   *
   * @remarks
   */
  idempotencyKey: string;
  /**
   * The agent revision the invocation ran (e.g. "a1b2c3d4").
   */
  agentRevision?: string | undefined;
  /**
   * The kind of event (e.g. "agent_invocation" for the request that started the run, "model_call" for a model call and the tool calls it requested, "tool_call" for an executed tool call and its output). Events recorded earlier use "llm_call" and "tool_result" for those same two kinds.
   *
   * @remarks
   */
  type: Type;
  /**
   * The event's details, whose shape depends on `type` (e.g. the model content and requested tool calls for "model_call"; the call's arguments, response, and MCP server URL for "tool_call"). Model and tool output and tool arguments are stored up to 32 KiB each, alongside the byte count, SHA-256 digest, and truncation flag of the complete value (e.g. `contentBytes`, `contentSha256`, `contentTruncated`).
   *
   * @remarks
   */
  payload: { [k: string]: any };
  /**
   * When the event occurred.
   */
  eventTime: Date;
};

/** @internal */
export const Type$inboundSchema: z.ZodMiniType<Type, unknown> = openEnums
  .inboundSchema(Type);

/** @internal */
export const AuditEvent$inboundSchema: z.ZodMiniType<AuditEvent, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      session_id: types.string(),
      idempotency_key: types.string(),
      agent_revision: types.optional(types.string()),
      type: Type$inboundSchema,
      payload: z.record(z.string(), z.any()),
      event_time: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "session_id": "sessionId",
        "idempotency_key": "idempotencyKey",
        "agent_revision": "agentRevision",
        "event_time": "eventTime",
      });
    }),
  );

export function auditEventFromJSON(
  jsonString: string,
): SafeParseResult<AuditEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditEvent' from JSON`,
  );
}
