/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * The kind of event (e.g. "llm_call" for a model call and the tool calls it requested, "tool_result" for a tool's output).
 *
 * @remarks
 */
export const Type = {
  LlmCall: "llm_call",
  ToolResult: "tool_result",
  RunFinished: "run_finished",
  RunFailed: "run_failed",
} as const;
/**
 * The kind of event (e.g. "llm_call" for a model call and the tool calls it requested, "tool_result" for a tool's output).
 *
 * @remarks
 */
export type Type = OpenEnum<typeof Type>;

export type AuditEvent = {
  /**
   * Stable identifier of this audit event within the session.
   */
  id: string;
  /**
   * The session this event belongs to.
   */
  sessionId: string;
  /**
   * The invocation (run) during which this event occurred.
   */
  invocationId: string;
  /**
   * The kind of event (e.g. "llm_call" for a model call and the tool calls it requested, "tool_result" for a tool's output).
   *
   * @remarks
   */
  type: Type;
  /**
   * The event's details, whose shape depends on `type` (e.g. the model content and requested tool calls for "llm_call").
   *
   * @remarks
   */
  payload: { [k: string]: any };
  /**
   * When the event occurred.
   */
  eventTime: Date;
};

/** @internal */
export const Type$inboundSchema: z.ZodMiniType<Type, unknown> = openEnums
  .inboundSchema(Type);

/** @internal */
export const AuditEvent$inboundSchema: z.ZodMiniType<AuditEvent, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      session_id: types.string(),
      invocation_id: types.string(),
      type: Type$inboundSchema,
      payload: z.record(z.string(), z.any()),
      event_time: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "session_id": "sessionId",
        "invocation_id": "invocationId",
        "event_time": "eventTime",
      });
    }),
  );

export function auditEventFromJSON(
  jsonString: string,
): SafeParseResult<AuditEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditEvent' from JSON`,
  );
}
