/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * The kind of event (e.g. "agent_invocation" for the request that started the invocation, "agent_step" for one turn, how it ended, and how long it took, "model_call" for a model call and the tool calls it requested, "tool_call" for an executed tool call and its output). Events recorded earlier use "llm_call", "tool_result", "run_failed" and "run_succeeded" for four of those kinds.
 *
 * @remarks
 */
export const AuditEventType = {
  AgentInvocation: "agent_invocation",
  AgentStep: "agent_step",
  ModelCall: "model_call",
  ToolCall: "tool_call",
  HarnessExit: "harness_exit",
  InvocationFailed: "invocation_failed",
  InvocationSucceeded: "invocation_succeeded",
  LlmCall: "llm_call",
  ToolResult: "tool_result",
  RunFailed: "run_failed",
  RunSucceeded: "run_succeeded",
} as const;
/**
 * The kind of event (e.g. "agent_invocation" for the request that started the invocation, "agent_step" for one turn, how it ended, and how long it took, "model_call" for a model call and the tool calls it requested, "tool_call" for an executed tool call and its output). Events recorded earlier use "llm_call", "tool_result", "run_failed" and "run_succeeded" for four of those kinds.
 *
 * @remarks
 */
export type AuditEventType = OpenEnum<typeof AuditEventType>;

export type AuditEvent = {
  /**
   * Stable identifier of this audit event within the session.
   */
  id: string;
  /**
   * The session this event belongs to.
   */
  sessionId: string;
  /**
   * Key of the invocation during which this event occurred.
   *
   * @remarks
   */
  invocationKey: string;
  /**
   * The agent revision the invocation ran (e.g. "a1b2c3d4").
   */
  agentRevision?: string | undefined;
  /**
   * The kind of event (e.g. "agent_invocation" for the request that started the invocation, "agent_step" for one turn, how it ended, and how long it took, "model_call" for a model call and the tool calls it requested, "tool_call" for an executed tool call and its output). Events recorded earlier use "llm_call", "tool_result", "run_failed" and "run_succeeded" for four of those kinds.
   *
   * @remarks
   */
  type: AuditEventType;
  /**
   * The event's details, whose shape depends on `type` (e.g. the model, its response, usage, and requested tool calls for "model_call"; the call's arguments, response, status, timing, and MCP server URL for "tool_call"). A large value may be stored truncated, marked by a flag such as `requestTruncated`; a truncated `request`, `response` or `content` also carries the byte count and SHA-256 digest of the complete value, in fields such as `requestBytes` and `requestSha256`. A "model_call"'s `request` is the input the model was given, so an invocation's final call using `output_format` includes turns Albus adds to obtain the JSON answer.
   *
   * @remarks
   */
  payload: { [k: string]: any };
  /**
   * When the event occurred.
   */
  eventTime: Date;
};

/** @internal */
export const AuditEventType$inboundSchema: z.ZodMiniType<
  AuditEventType,
  unknown
> = openEnums.inboundSchema(AuditEventType);

/** @internal */
export const AuditEvent$inboundSchema: z.ZodMiniType<AuditEvent, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      session_id: types.string(),
      invocation_key: types.string(),
      agent_revision: types.optional(types.string()),
      type: AuditEventType$inboundSchema,
      payload: z.record(z.string(), z.any()),
      event_time: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "session_id": "sessionId",
        "invocation_key": "invocationKey",
        "agent_revision": "agentRevision",
        "event_time": "eventTime",
      });
    }),
  );

export function auditEventFromJSON(
  jsonString: string,
): SafeParseResult<AuditEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditEvent' from JSON`,
  );
}
