/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type AuthenticatedApiKey = {
  /**
   * Display name of the API key (e.g. "ci-deploy").
   */
  name: string;
  /**
   * The organization this key acts in.
   */
  organizationId: string;
};

/** @internal */
export const AuthenticatedApiKey$inboundSchema: z.ZodMiniType<
  AuthenticatedApiKey,
  unknown
> = z.pipe(
  z.object({
    name: types.string(),
    organization_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
    });
  }),
);

export function authenticatedApiKeyFromJSON(
  jsonString: string,
): SafeParseResult<AuthenticatedApiKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthenticatedApiKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthenticatedApiKey' from JSON`,
  );
}
