/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * A static bearer token sent with every request.
 */
export type BearerTokenAuth = {
  type: "bearer";
  /**
   * The token, as a secret reference (e.g. "albus.sh/secrets/mcp-token"), never a raw value.
   *
   * @remarks
   */
  token: string;
};

/** @internal */
export const BearerTokenAuth$inboundSchema: z.ZodMiniType<
  BearerTokenAuth,
  unknown
> = z.object({
  type: types.literal("bearer"),
  token: types.string(),
});
/** @internal */
export type BearerTokenAuth$Outbound = {
  type: "bearer";
  token: string;
};

/** @internal */
export const BearerTokenAuth$outboundSchema: z.ZodMiniType<
  BearerTokenAuth$Outbound,
  BearerTokenAuth
> = z.object({
  type: z.literal("bearer"),
  token: z.string(),
});

export function bearerTokenAuthToJSON(
  bearerTokenAuth: BearerTokenAuth,
): string {
  return JSON.stringify(BearerTokenAuth$outboundSchema.parse(bearerTokenAuth));
}
export function bearerTokenAuthFromJSON(
  jsonString: string,
): SafeParseResult<BearerTokenAuth, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BearerTokenAuth$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BearerTokenAuth' from JSON`,
  );
}
