/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type CancelSessionResponse = {
  /**
   * The key of the invocation being canceled.
   */
  invocationKey: string;
};

/** @internal */
export const CancelSessionResponse$inboundSchema: z.ZodMiniType<
  CancelSessionResponse,
  unknown
> = z.pipe(
  z.object({
    invocation_key: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "invocation_key": "invocationKey",
    });
  }),
);

export function cancelSessionResponseFromJSON(
  jsonString: string,
): SafeParseResult<CancelSessionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CancelSessionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CancelSessionResponse' from JSON`,
  );
}
