/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Offers the model a persistent Linux sandbox to run commands in.
 *
 * @remarks
 */
export type ComputerTool = {};

/** @internal */
export const ComputerTool$inboundSchema: z.ZodMiniType<ComputerTool, unknown> =
  z.object({});
/** @internal */
export type ComputerTool$Outbound = {};

/** @internal */
export const ComputerTool$outboundSchema: z.ZodMiniType<
  ComputerTool$Outbound,
  ComputerTool
> = z.object({});

export function computerToolToJSON(computerTool: ComputerTool): string {
  return JSON.stringify(ComputerTool$outboundSchema.parse(computerTool));
}
export function computerToolFromJSON(
  jsonString: string,
): SafeParseResult<ComputerTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ComputerTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ComputerTool' from JSON`,
  );
}
