/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type CreateTokenResponse = {
  /**
   * Globally unique lookup identifier.
   */
  id: string;
  /**
   * Human-readable display name.
   */
  name: string;
  /**
   * The full API token value (format: alb-<id>-<secret>).
   *
   * @remarks
   * Returned only at creation time — it cannot be retrieved again.
   */
  token: string;
  createdAt: Date;
};

/** @internal */
export const CreateTokenResponse$inboundSchema: z.ZodMiniType<
  CreateTokenResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    token: types.string(),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
    });
  }),
);

export function createTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTokenResponse' from JSON`,
  );
}
