/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateSecretRequest = {
  name: string;
  /**
   * The secret value.
   */
  value: string;
};

/** @internal */
export type CreateSecretRequest$Outbound = {
  name: string;
  value: string;
};

/** @internal */
export const CreateSecretRequest$outboundSchema: z.ZodMiniType<
  CreateSecretRequest$Outbound,
  CreateSecretRequest
> = z.object({
  name: z.string(),
  value: z.string(),
});

export function createSecretRequestToJSON(
  createSecretRequest: CreateSecretRequest,
): string {
  return JSON.stringify(
    CreateSecretRequest$outboundSchema.parse(createSecretRequest),
  );
}
