/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateCheckoutRequest = {
  /**
   * Whole US dollars of credit to buy (e.g. 20).
   */
  amountUsd: number;
  /**
   * Where the buyer's browser goes after paying. Must be https (or http on localhost).
   *
   * @remarks
   */
  successUrl: string;
  /**
   * Where the buyer's browser goes if they back out. Must be https (or http on localhost).
   *
   * @remarks
   */
  cancelUrl: string;
};

/** @internal */
export type CreateCheckoutRequest$Outbound = {
  amount_usd: number;
  success_url: string;
  cancel_url: string;
};

/** @internal */
export const CreateCheckoutRequest$outboundSchema: z.ZodMiniType<
  CreateCheckoutRequest$Outbound,
  CreateCheckoutRequest
> = z.pipe(
  z.object({
    amountUsd: z.int(),
    successUrl: z.string(),
    cancelUrl: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      amountUsd: "amount_usd",
      successUrl: "success_url",
      cancelUrl: "cancel_url",
    });
  }),
);

export function createCheckoutRequestToJSON(
  createCheckoutRequest: CreateCheckoutRequest,
): string {
  return JSON.stringify(
    CreateCheckoutRequest$outboundSchema.parse(createCheckoutRequest),
  );
}
