/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type CreateCheckoutResponse = {
  /**
   * The payment page to send the buyer's browser to.
   */
  url: string;
};

/** @internal */
export const CreateCheckoutResponse$inboundSchema: z.ZodMiniType<
  CreateCheckoutResponse,
  unknown
> = z.object({
  url: types.string(),
});

export function createCheckoutResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateCheckoutResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateCheckoutResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateCheckoutResponse' from JSON`,
  );
}
