/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateTokenRequest = {
  name: string;
};

/** @internal */
export type CreateTokenRequest$Outbound = {
  name: string;
};

/** @internal */
export const CreateTokenRequest$outboundSchema: z.ZodMiniType<
  CreateTokenRequest$Outbound,
  CreateTokenRequest
> = z.object({
  name: z.string(),
});

export function createTokenRequestToJSON(
  createTokenRequest: CreateTokenRequest,
): string {
  return JSON.stringify(
    CreateTokenRequest$outboundSchema.parse(createTokenRequest),
  );
}
