/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Role to grant the invitee.
 */
export const CreateInviteRequestRole = {
  Admin: "admin",
  Member: "member",
} as const;
/**
 * Role to grant the invitee.
 */
export type CreateInviteRequestRole = ClosedEnum<
  typeof CreateInviteRequestRole
>;

export type CreateInviteRequest = {
  /**
   * Email address of the person to invite.
   */
  email: string;
  /**
   * Role to grant the invitee.
   */
  role?: CreateInviteRequestRole | undefined;
};

/** @internal */
export const CreateInviteRequestRole$outboundSchema: z.ZodMiniEnum<
  typeof CreateInviteRequestRole
> = z.enum(CreateInviteRequestRole);

/** @internal */
export type CreateInviteRequest$Outbound = {
  email: string;
  role: string;
};

/** @internal */
export const CreateInviteRequest$outboundSchema: z.ZodMiniType<
  CreateInviteRequest$Outbound,
  CreateInviteRequest
> = z.object({
  email: z.string(),
  role: z._default(CreateInviteRequestRole$outboundSchema, "member"),
});

export function createInviteRequestToJSON(
  createInviteRequest: CreateInviteRequest,
): string {
  return JSON.stringify(
    CreateInviteRequest$outboundSchema.parse(createInviteRequest),
  );
}
