/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * Role to grant the invitee. Defaults to admin when inviting to a new organization and member when inviting into an existing one.
 *
 * @remarks
 */
export const CreateInviteRequestRole = {
  Admin: "admin",
  Member: "member",
} as const;
/**
 * Role to grant the invitee. Defaults to admin when inviting to a new organization and member when inviting into an existing one.
 *
 * @remarks
 */
export type CreateInviteRequestRole = ClosedEnum<
  typeof CreateInviteRequestRole
>;

export type CreateInviteRequest = {
  /**
   * Email address of the person to invite.
   */
  email: string;
  /**
   * Role to grant the invitee. Defaults to admin when inviting to a new organization and member when inviting into an existing one.
   *
   * @remarks
   */
  role?: CreateInviteRequestRole | undefined;
  /**
   * Organization to invite the user into (e.g. "42"). Omit to create a new organization for the user on their first sign-in.
   *
   * @remarks
   */
  organizationId?: string | undefined;
};

/** @internal */
export const CreateInviteRequestRole$outboundSchema: z.ZodMiniEnum<
  typeof CreateInviteRequestRole
> = z.enum(CreateInviteRequestRole);

/** @internal */
export type CreateInviteRequest$Outbound = {
  email: string;
  role?: string | undefined;
  organization_id?: string | undefined;
};

/** @internal */
export const CreateInviteRequest$outboundSchema: z.ZodMiniType<
  CreateInviteRequest$Outbound,
  CreateInviteRequest
> = z.pipe(
  z.object({
    email: z.string(),
    role: z.optional(CreateInviteRequestRole$outboundSchema),
    organizationId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
    });
  }),
);

export function createInviteRequestToJSON(
  createInviteRequest: CreateInviteRequest,
): string {
  return JSON.stringify(
    CreateInviteRequest$outboundSchema.parse(createInviteRequest),
  );
}
