/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type CreditBalanceResponse = {
  /**
   * Your current credit balance as a decimal USD string (e.g. "14.99"). Negative when overdrawn.
   *
   * @remarks
   */
  balanceUsd: string;
};

/** @internal */
export const CreditBalanceResponse$inboundSchema: z.ZodMiniType<
  CreditBalanceResponse,
  unknown
> = z.pipe(
  z.object({
    balance_usd: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "balance_usd": "balanceUsd",
    });
  }),
);

export function creditBalanceResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreditBalanceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreditBalanceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditBalanceResponse' from JSON`,
  );
}
