/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * What moved the balance: a paid purchase, an operator grant, a usage charge, or a manual adjustment.
 *
 * @remarks
 */
export const CreditLedgerEntryKind = {
  Purchase: "purchase",
  Grant: "grant",
  UsageBurn: "usage_burn",
  Adjustment: "adjustment",
} as const;
/**
 * What moved the balance: a paid purchase, an operator grant, a usage charge, or a manual adjustment.
 *
 * @remarks
 */
export type CreditLedgerEntryKind = OpenEnum<typeof CreditLedgerEntryKind>;

export type CreditLedgerEntry = {
  /**
   * What moved the balance: a paid purchase, an operator grant, a usage charge, or a manual adjustment.
   *
   * @remarks
   */
  kind: CreditLedgerEntryKind;
  /**
   * The signed decimal USD amount the entry moved the balance by: positive for money in, negative for usage charged.
   *
   * @remarks
   */
  amountUsd: string;
  /**
   * Identifies what the entry paid for or charged (e.g. the payment for a purchase, the metering window for a usage charge).
   *
   * @remarks
   */
  reference: string;
  /**
   * When the entry was recorded.
   */
  createdAt: Date;
};

/** @internal */
export const CreditLedgerEntryKind$inboundSchema: z.ZodMiniType<
  CreditLedgerEntryKind,
  unknown
> = openEnums.inboundSchema(CreditLedgerEntryKind);

/** @internal */
export const CreditLedgerEntry$inboundSchema: z.ZodMiniType<
  CreditLedgerEntry,
  unknown
> = z.pipe(
  z.object({
    kind: CreditLedgerEntryKind$inboundSchema,
    amount_usd: types.string(),
    reference: types.string(),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "amount_usd": "amountUsd",
      "created_at": "createdAt",
    });
  }),
);

export function creditLedgerEntryFromJSON(
  jsonString: string,
): SafeParseResult<CreditLedgerEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreditLedgerEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditLedgerEntry' from JSON`,
  );
}
