/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Invite = {
  /**
   * Invitation identifier
   */
  id: string;
  /**
   * Invited email address
   */
  email: string;
  /**
   * Role the invitee will be granted
   */
  role: string;
  /**
   * Organization the invitee will join. Absent when the invitation creates a new organization on first sign-in.
   *
   * @remarks
   */
  organizationId?: string | undefined;
};

/** @internal */
export const Invite$inboundSchema: z.ZodMiniType<Invite, unknown> = z.pipe(
  z.object({
    id: types.string(),
    email: types.string(),
    role: types.string(),
    organization_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
    });
  }),
);

export function inviteFromJSON(
  jsonString: string,
): SafeParseResult<Invite, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Invite$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Invite' from JSON`,
  );
}
