/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { AgentMeta, AgentMeta$inboundSchema } from "./agent-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ListAgentsResponse = {
  agents: Array<AgentMeta>;
};

/** @internal */
export const ListAgentsResponse$inboundSchema: z.ZodMiniType<
  ListAgentsResponse,
  unknown
> = z.object({
  agents: z.array(AgentMeta$inboundSchema),
});

export function listAgentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAgentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAgentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAgentsResponse' from JSON`,
  );
}
