/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Memory, Memory$inboundSchema } from "./memory.js";

export type ListMemoriesResponse = {
  memories: Array<Memory>;
  /**
   * Cursor for the next page. Pass it as `after` to fetch the following memories. Omitted when there are no more memories.
   *
   * @remarks
   */
  nextCursor?: string | undefined;
};

/** @internal */
export const ListMemoriesResponse$inboundSchema: z.ZodMiniType<
  ListMemoriesResponse,
  unknown
> = z.pipe(
  z.object({
    memories: z.array(Memory$inboundSchema),
    next_cursor: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function listMemoriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMemoriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMemoriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMemoriesResponse' from JSON`,
  );
}
