/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { AuditEvent, AuditEvent$inboundSchema } from "./audit-event.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ListAuditEventsResponse = {
  events: Array<AuditEvent>;
  /**
   * Cursor for the next page. Pass it as `after` to fetch the following events. Omitted when there are no more events.
   *
   * @remarks
   */
  nextCursor?: string | undefined;
};

/** @internal */
export const ListAuditEventsResponse$inboundSchema: z.ZodMiniType<
  ListAuditEventsResponse,
  unknown
> = z.pipe(
  z.object({
    events: z.array(AuditEvent$inboundSchema),
    next_cursor: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function listAuditEventsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAuditEventsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAuditEventsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAuditEventsResponse' from JSON`,
  );
}
