/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Token, Token$inboundSchema } from "./token.js";

export type ListTokensResponse = {
  tokens: Array<Token>;
};

/** @internal */
export const ListTokensResponse$inboundSchema: z.ZodMiniType<
  ListTokensResponse,
  unknown
> = z.object({
  tokens: z.array(Token$inboundSchema),
});

export function listTokensResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListTokensResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTokensResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTokensResponse' from JSON`,
  );
}
