/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { MemoryGroup, MemoryGroup$inboundSchema } from "./memory-group.js";

export type ListMemoryGroupsResponse = {
  memoryGroups: Array<MemoryGroup>;
  /**
   * Cursor for the next page. Pass it as `after` to fetch the following groups. Omitted when there are no more groups.
   *
   * @remarks
   */
  nextCursor?: string | undefined;
};

/** @internal */
export const ListMemoryGroupsResponse$inboundSchema: z.ZodMiniType<
  ListMemoryGroupsResponse,
  unknown
> = z.pipe(
  z.object({
    memory_groups: z.array(MemoryGroup$inboundSchema),
    next_cursor: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "memory_groups": "memoryGroups",
      "next_cursor": "nextCursor",
    });
  }),
);

export function listMemoryGroupsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMemoryGroupsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMemoryGroupsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMemoryGroupsResponse' from JSON`,
  );
}
