/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  OrganizationMember,
  OrganizationMember$inboundSchema,
} from "./organization-member.js";

export type ListOrganizationMembersResponse = {
  members: Array<OrganizationMember>;
};

/** @internal */
export const ListOrganizationMembersResponse$inboundSchema: z.ZodMiniType<
  ListOrganizationMembersResponse,
  unknown
> = z.object({
  members: z.array(OrganizationMember$inboundSchema),
});

export function listOrganizationMembersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListOrganizationMembersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListOrganizationMembersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOrganizationMembersResponse' from JSON`,
  );
}
