/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  CreditLedgerEntry,
  CreditLedgerEntry$inboundSchema,
} from "./credit-ledger-entry.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ListCreditLedgerResponse = {
  entries: Array<CreditLedgerEntry>;
  /**
   * Cursor for the next page. Pass it as `after` to fetch the following entries. Omitted when there are no more entries.
   *
   * @remarks
   */
  nextCursor?: string | undefined;
};

/** @internal */
export const ListCreditLedgerResponse$inboundSchema: z.ZodMiniType<
  ListCreditLedgerResponse,
  unknown
> = z.pipe(
  z.object({
    entries: z.array(CreditLedgerEntry$inboundSchema),
    next_cursor: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function listCreditLedgerResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCreditLedgerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCreditLedgerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCreditLedgerResponse' from JSON`,
  );
}
