/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { ModelMeta, ModelMeta$inboundSchema } from "./model-meta.js";

export type ListModelsResponse = {
  models: Array<ModelMeta>;
};

/** @internal */
export const ListModelsResponse$inboundSchema: z.ZodMiniType<
  ListModelsResponse,
  unknown
> = z.object({
  models: z.array(ModelMeta$inboundSchema),
});

export function listModelsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListModelsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListModelsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListModelsResponse' from JSON`,
  );
}
