/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { TraceSummary, TraceSummary$inboundSchema } from "./trace-summary.js";

export type ListTracesResponse = {
  /**
   * This page of invocations, newest first. It can hold fewer than `limit`, or none at all, while `next_cursor` is present.
   *
   * @remarks
   */
  traces: Array<TraceSummary>;
  /**
   * Cursor for the next page. Pass it as `after`, with no filters or with every filter this listing used repeated exactly, to fetch the following traces. Present whenever there may be more traces, however few this page returned; omitted only once there are none left.
   *
   * @remarks
   */
  nextCursor?: string | undefined;
};

/** @internal */
export const ListTracesResponse$inboundSchema: z.ZodMiniType<
  ListTracesResponse,
  unknown
> = z.pipe(
  z.object({
    traces: z.array(TraceSummary$inboundSchema),
    next_cursor: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function listTracesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListTracesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTracesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTracesResponse' from JSON`,
  );
}
