/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Session, Session$inboundSchema } from "./session.js";

export type ListSessionsResponse = {
  sessions: Array<Session>;
};

/** @internal */
export const ListSessionsResponse$inboundSchema: z.ZodMiniType<
  ListSessionsResponse,
  unknown
> = z.object({
  sessions: z.array(Session$inboundSchema),
});

export function listSessionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSessionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSessionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSessionsResponse' from JSON`,
  );
}
