/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Invite, Invite$inboundSchema } from "./invite.js";

export type ListInvitesResponse = {
  invites: Array<Invite>;
};

/** @internal */
export const ListInvitesResponse$inboundSchema: z.ZodMiniType<
  ListInvitesResponse,
  unknown
> = z.object({
  invites: z.array(Invite$inboundSchema),
});

export function listInvitesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListInvitesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListInvitesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListInvitesResponse' from JSON`,
  );
}
