/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MCPServerAuth,
  MCPServerAuth$inboundSchema,
  MCPServerAuth$Outbound,
  MCPServerAuth$outboundSchema,
} from "./mcp-server-auth.js";

export type MCPServer = {
  /**
   * Unique alias for the server. It prefixes the server's tool names (e.g. "github" exposes its search tool as "github__search").
   *
   * @remarks
   */
  name: string;
  /**
   * The server's Streamable HTTP endpoint.
   */
  url: string;
  /**
   * HTTP headers sent to the server, with secret values as secret references (e.g. "albus.sh/secrets/github-mcp"); this is also where to send an API key or other non-Bearer credential. A literal value is sent as is, is returned as "<literal>", and does not change the agent's revision.
   *
   * @remarks
   */
  headers?: { [k: string]: string } | undefined;
  /**
   * The server tools the model may call. Omit to allow all of them.
   *
   * @remarks
   */
  allowedTools?: Array<string> | undefined;
  /**
   * How Albus authenticates to the server. Omit for the default, AlbusIdentityJWTAuth, which needs no credential from you; see that schema for what the server must verify. Setting "headers.Authorization" instead sends that header verbatim.
   *
   * @remarks
   */
  auth?: MCPServerAuth | undefined;
};

/** @internal */
export const MCPServer$inboundSchema: z.ZodMiniType<MCPServer, unknown> = z
  .pipe(
    z.object({
      name: types.string(),
      url: types.string(),
      headers: types.optional(z.record(z.string(), types.string())),
      allowed_tools: types.optional(z.array(types.string())),
      auth: types.optional(MCPServerAuth$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        "allowed_tools": "allowedTools",
      });
    }),
  );
/** @internal */
export type MCPServer$Outbound = {
  name: string;
  url: string;
  headers?: { [k: string]: string } | undefined;
  allowed_tools?: Array<string> | undefined;
  auth?: MCPServerAuth$Outbound | undefined;
};

/** @internal */
export const MCPServer$outboundSchema: z.ZodMiniType<
  MCPServer$Outbound,
  MCPServer
> = z.pipe(
  z.object({
    name: z.string(),
    url: z.string(),
    headers: z.optional(z.record(z.string(), z.string())),
    allowedTools: z.optional(z.array(z.string())),
    auth: z.optional(MCPServerAuth$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      allowedTools: "allowed_tools",
    });
  }),
);

export function mcpServerToJSON(mcpServer: MCPServer): string {
  return JSON.stringify(MCPServer$outboundSchema.parse(mcpServer));
}
export function mcpServerFromJSON(
  jsonString: string,
): SafeParseResult<MCPServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MCPServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MCPServer' from JSON`,
  );
}
