/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AlbusIdentityJWTAuth,
  AlbusIdentityJWTAuth$inboundSchema,
  AlbusIdentityJWTAuth$Outbound,
  AlbusIdentityJWTAuth$outboundSchema,
} from "./albus-identity-jwt-auth.js";
import {
  BearerTokenAuth,
  BearerTokenAuth$inboundSchema,
  BearerTokenAuth$Outbound,
  BearerTokenAuth$outboundSchema,
} from "./bearer-token-auth.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  OAuth2ClientCredentialsAuth,
  OAuth2ClientCredentialsAuth$inboundSchema,
  OAuth2ClientCredentialsAuth$Outbound,
  OAuth2ClientCredentialsAuth$outboundSchema,
} from "./o-auth2-client-credentials-auth.js";

/**
 * The credential Albus presents to an MCP server, chosen by type.
 *
 * @remarks
 */
export type MCPServerAuth =
  | AlbusIdentityJWTAuth
  | OAuth2ClientCredentialsAuth
  | BearerTokenAuth
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const MCPServerAuth$inboundSchema: z.ZodMiniType<
  MCPServerAuth,
  unknown
> = discriminatedUnion("type", {
  albus_identity_jwt: AlbusIdentityJWTAuth$inboundSchema,
  oauth2_client_credentials: OAuth2ClientCredentialsAuth$inboundSchema,
  bearer: BearerTokenAuth$inboundSchema,
});
/** @internal */
export type MCPServerAuth$Outbound =
  | AlbusIdentityJWTAuth$Outbound
  | OAuth2ClientCredentialsAuth$Outbound
  | BearerTokenAuth$Outbound;

/** @internal */
export const MCPServerAuth$outboundSchema: z.ZodMiniType<
  MCPServerAuth$Outbound,
  MCPServerAuth
> = z.union([
  AlbusIdentityJWTAuth$outboundSchema,
  OAuth2ClientCredentialsAuth$outboundSchema,
  BearerTokenAuth$outboundSchema,
  z.pipe(
    z.custom<discriminatedUnionTypes.Unknown<"type">>(
      discriminatedUnionTypes.isUnknown,
    ),
    z.transform((value) => value.raw as MCPServerAuth$Outbound),
  ),
]);

export function mcpServerAuthToJSON(mcpServerAuth: MCPServerAuth): string {
  return JSON.stringify(MCPServerAuth$outboundSchema.parse(mcpServerAuth));
}
export function mcpServerAuthFromJSON(
  jsonString: string,
): SafeParseResult<MCPServerAuth, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MCPServerAuth$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MCPServerAuth' from JSON`,
  );
}
