/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type MCPServer = {
  /**
   * Unique alias for the server. It prefixes the server's tool names (e.g. "github" exposes its search tool as "github__search").
   *
   * @remarks
   */
  name: string;
  /**
   * The server's Streamable HTTP endpoint.
   */
  url: string;
  /**
   * HTTP headers sent to the server. Values are secret references (e.g. "albus.sh/secrets/github-mcp"), not raw secret values.
   *
   * @remarks
   */
  headers?: { [k: string]: string } | undefined;
  /**
   * The server tools the model may call. Omit to allow all of them.
   *
   * @remarks
   */
  allowedTools?: Array<string> | undefined;
};

/** @internal */
export type MCPServer$Outbound = {
  name: string;
  url: string;
  headers?: { [k: string]: string } | undefined;
  allowed_tools?: Array<string> | undefined;
};

/** @internal */
export const MCPServer$outboundSchema: z.ZodMiniType<
  MCPServer$Outbound,
  MCPServer
> = z.pipe(
  z.object({
    name: z.string(),
    url: z.string(),
    headers: z.optional(z.record(z.string(), z.string())),
    allowedTools: z.optional(z.array(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      allowedTools: "allowed_tools",
    });
  }),
);

export function mcpServerToJSON(mcpServer: MCPServer): string {
  return JSON.stringify(MCPServer$outboundSchema.parse(mcpServer));
}
