/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const Generation = {
  Agent: "agent",
  EndOfInvocation: "end_of_invocation",
} as const;
export type Generation = OpenEnum<typeof Generation>;

/**
 * Configures durable memory shared by invocations in the same group.
 *
 * @remarks
 */
export type MemoryConfig = {
  /**
   * Key identifying invocations that share memory.
   */
  group: string;
  /**
   * Points when this agent may generate memories.
   */
  generation: Array<Generation>;
};

/** @internal */
export const Generation$inboundSchema: z.ZodMiniType<Generation, unknown> =
  openEnums.inboundSchema(Generation);
/** @internal */
export const Generation$outboundSchema: z.ZodMiniType<string, Generation> =
  openEnums.outboundSchema(Generation);

/** @internal */
export const MemoryConfig$inboundSchema: z.ZodMiniType<MemoryConfig, unknown> =
  z.object({
    group: types.string(),
    generation: z.array(Generation$inboundSchema),
  });
/** @internal */
export type MemoryConfig$Outbound = {
  group: string;
  generation: Array<string>;
};

/** @internal */
export const MemoryConfig$outboundSchema: z.ZodMiniType<
  MemoryConfig$Outbound,
  MemoryConfig
> = z.object({
  group: z.string(),
  generation: z.array(Generation$outboundSchema),
});

export function memoryConfigToJSON(memoryConfig: MemoryConfig): string {
  return JSON.stringify(MemoryConfig$outboundSchema.parse(memoryConfig));
}
export function memoryConfigFromJSON(
  jsonString: string,
): SafeParseResult<MemoryConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MemoryConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MemoryConfig' from JSON`,
  );
}
