/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type MemoryGroup = {
  /**
   * The group's name — the `memory.group` value agents sharing its memories run with. Read its memories at `GET /memorygroups/{group}`.
   *
   * @remarks
   */
  key: string;
  /**
   * Number of memories agents in the group currently read.
   */
  activeMemories: number;
  /**
   * When an agent first ran with this group.
   */
  createdAt: Date;
};

/** @internal */
export const MemoryGroup$inboundSchema: z.ZodMiniType<MemoryGroup, unknown> = z
  .pipe(
    z.object({
      key: types.string(),
      active_memories: types.number(),
      created_at: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "active_memories": "activeMemories",
        "created_at": "createdAt",
      });
    }),
  );

export function memoryGroupFromJSON(
  jsonString: string,
): SafeParseResult<MemoryGroup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MemoryGroup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MemoryGroup' from JSON`,
  );
}
