/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Always `active`; only memories agents read are listed.
 */
export const MemoryStatus = {
  Active: "active",
} as const;
/**
 * Always `active`; only memories agents read are listed.
 */
export type MemoryStatus = ClosedEnum<typeof MemoryStatus>;

export type Memory = {
  /**
   * Identifier of this memory; pass it to `DELETE /memorygroups/{group}/memories/{id}`.
   *
   * @remarks
   */
  id: string;
  /**
   * The fact remembered, as the agent stated it.
   */
  content: string;
  /**
   * Always `active`; only memories agents read are listed.
   */
  status: MemoryStatus;
  /**
   * When the memory was remembered.
   */
  createdAt: Date;
  /**
   * Customer-provided session identifier that produced the memory.
   *
   * @remarks
   */
  sourceSession?: string | undefined;
  /**
   * Invocation identifier that produced the memory.
   */
  sourceInvocation?: string | undefined;
};

/** @internal */
export const MemoryStatus$inboundSchema: z.ZodMiniEnum<typeof MemoryStatus> = z
  .enum(MemoryStatus);

/** @internal */
export const Memory$inboundSchema: z.ZodMiniType<Memory, unknown> = z.pipe(
  z.object({
    id: types.string(),
    content: types.string(),
    status: MemoryStatus$inboundSchema,
    created_at: types.date(),
    source_session: types.optional(types.string()),
    source_invocation: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "source_session": "sourceSession",
      "source_invocation": "sourceInvocation",
    });
  }),
);

export function memoryFromJSON(
  jsonString: string,
): SafeParseResult<Memory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Memory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Memory' from JSON`,
  );
}
