/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { ModelPricing, ModelPricing$inboundSchema } from "./model-pricing.js";

/**
 * A model Albus can run, and the provider serving it.
 */
export type ModelMeta = {
  /**
   * Model identifier to send as the agent's model name (e.g. "gemini-3.6-flash").
   *
   * @remarks
   */
  name: string;
  /**
   * Provider serving this model (e.g. "google_agent_studio", or "open_weight" for open-weight models).
   *
   * @remarks
   */
  provider: string;
  /**
   * What the model currently costs, as decimal USD strings per one million tokens (e.g. "1.25"). Absent when the model is not yet priced.
   *
   * @remarks
   */
  pricing?: ModelPricing | undefined;
};

/** @internal */
export const ModelMeta$inboundSchema: z.ZodMiniType<ModelMeta, unknown> = z
  .object({
    name: types.string(),
    provider: types.string(),
    pricing: types.optional(ModelPricing$inboundSchema),
  });

export function modelMetaFromJSON(
  jsonString: string,
): SafeParseResult<ModelMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelMeta' from JSON`,
  );
}
