/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * What the model currently costs, as decimal USD strings per one million tokens (e.g. "1.25"). Absent when the model is not yet priced.
 *
 * @remarks
 */
export type ModelPricing = {
  /**
   * Price per million input tokens.
   */
  inputUsdPerMtok: string;
  /**
   * Price per million cached input tokens.
   */
  cachedInputUsdPerMtok: string;
  /**
   * Price per million output tokens.
   */
  outputUsdPerMtok: string;
  /**
   * Price per million reasoning (thinking) tokens.
   */
  thoughtsUsdPerMtok: string;
};

/** @internal */
export const ModelPricing$inboundSchema: z.ZodMiniType<ModelPricing, unknown> =
  z.pipe(
    z.object({
      input_usd_per_mtok: types.string(),
      cached_input_usd_per_mtok: types.string(),
      output_usd_per_mtok: types.string(),
      thoughts_usd_per_mtok: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "input_usd_per_mtok": "inputUsdPerMtok",
        "cached_input_usd_per_mtok": "cachedInputUsdPerMtok",
        "output_usd_per_mtok": "outputUsdPerMtok",
        "thoughts_usd_per_mtok": "thoughtsUsdPerMtok",
      });
    }),
  );

export function modelPricingFromJSON(
  jsonString: string,
): SafeParseResult<ModelPricing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelPricing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelPricing' from JSON`,
  );
}
