/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  Provider,
  Provider$Outbound,
  Provider$outboundSchema,
} from "./provider.js";

export type Model = {
  /**
   * Model identifier (e.g. "gemini-2.5-flash", "claude-opus-4").
   */
  name: string;
  provider?: Provider | undefined;
};

/** @internal */
export type Model$Outbound = {
  name: string;
  provider?: Provider$Outbound | undefined;
};

/** @internal */
export const Model$outboundSchema: z.ZodMiniType<Model$Outbound, Model> = z
  .object({
    name: z.string(),
    provider: z.optional(Provider$outboundSchema),
  });

export function modelToJSON(model: Model): string {
  return JSON.stringify(Model$outboundSchema.parse(model));
}
