/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * An access token obtained from your identity provider with the OAuth 2.0 client credentials grant.
 *
 * @remarks
 */
export type OAuth2ClientCredentialsAuth = {
  type: "oauth2_client_credentials";
  /**
   * The identity provider's HTTPS token endpoint.
   */
  tokenUrl: string;
  /**
   * The client identifier, as a secret reference or a literal.
   *
   * @remarks
   */
  clientId: string;
  /**
   * The client secret, as a secret reference (e.g. "albus.sh/secrets/idp-client-secret"), never a raw value.
   *
   * @remarks
   */
  clientSecret: string;
  /**
   * The audience requested from the identity provider.
   */
  audience?: string | undefined;
  /**
   * The scopes requested from the identity provider.
   */
  scopes?: Array<string> | undefined;
};

/** @internal */
export const OAuth2ClientCredentialsAuth$inboundSchema: z.ZodMiniType<
  OAuth2ClientCredentialsAuth,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("oauth2_client_credentials"),
    token_url: types.string(),
    client_id: types.string(),
    client_secret: types.string(),
    audience: types.optional(types.string()),
    scopes: types.optional(z.array(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "token_url": "tokenUrl",
      "client_id": "clientId",
      "client_secret": "clientSecret",
    });
  }),
);
/** @internal */
export type OAuth2ClientCredentialsAuth$Outbound = {
  type: "oauth2_client_credentials";
  token_url: string;
  client_id: string;
  client_secret: string;
  audience?: string | undefined;
  scopes?: Array<string> | undefined;
};

/** @internal */
export const OAuth2ClientCredentialsAuth$outboundSchema: z.ZodMiniType<
  OAuth2ClientCredentialsAuth$Outbound,
  OAuth2ClientCredentialsAuth
> = z.pipe(
  z.object({
    type: z.literal("oauth2_client_credentials"),
    tokenUrl: z.string(),
    clientId: z.string(),
    clientSecret: z.string(),
    audience: z.optional(z.string()),
    scopes: z.optional(z.array(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      tokenUrl: "token_url",
      clientId: "client_id",
      clientSecret: "client_secret",
    });
  }),
);

export function oAuth2ClientCredentialsAuthToJSON(
  oAuth2ClientCredentialsAuth: OAuth2ClientCredentialsAuth,
): string {
  return JSON.stringify(
    OAuth2ClientCredentialsAuth$outboundSchema.parse(
      oAuth2ClientCredentialsAuth,
    ),
  );
}
export function oAuth2ClientCredentialsAuthFromJSON(
  jsonString: string,
): SafeParseResult<OAuth2ClientCredentialsAuth, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OAuth2ClientCredentialsAuth$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OAuth2ClientCredentialsAuth' from JSON`,
  );
}
