/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Organization = {
  /**
   * Organization identifier
   */
  id: string;
  /**
   * Organization display name
   */
  name: string;
  /**
   * When the organization was created.
   */
  createdAt: Date;
};

/** @internal */
export const Organization$inboundSchema: z.ZodMiniType<Organization, unknown> =
  z.pipe(
    z.object({
      id: types.string(),
      name: types.string(),
      created_at: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "created_at": "createdAt",
      });
    }),
  );

export function organizationFromJSON(
  jsonString: string,
): SafeParseResult<Organization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Organization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Organization' from JSON`,
  );
}
