/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type OrganizationMembership = {
  /**
   * Organization identifier
   */
  id: string;
  /**
   * Organization display name
   */
  name: string;
  /**
   * Roles the user holds in this organization
   */
  roles: Array<string>;
};

/** @internal */
export const OrganizationMembership$inboundSchema: z.ZodMiniType<
  OrganizationMembership,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  roles: z.array(types.string()),
});

export function organizationMembershipFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationMembership, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationMembership$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationMembership' from JSON`,
  );
}
