/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Role, Role$inboundSchema } from "./role.js";

export type OrganizationMember = {
  /**
   * User identifier
   */
  userId: string;
  /**
   * Email address
   */
  email: string;
  /**
   * Display name
   */
  name: string;
  /**
   * A member's role in an organization.
   */
  role: Role;
  /**
   * When the user joined the organization.
   */
  joinedAt: Date;
};

/** @internal */
export const OrganizationMember$inboundSchema: z.ZodMiniType<
  OrganizationMember,
  unknown
> = z.pipe(
  z.object({
    user_id: types.string(),
    email: types.string(),
    name: types.string(),
    role: Role$inboundSchema,
    joined_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "user_id": "userId",
      "joined_at": "joinedAt",
    });
  }),
);

export function organizationMemberFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationMember, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationMember$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationMember' from JSON`,
  );
}
