/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Provider = {
  /**
   * Provider name (e.g. "openai", "gemini", "vertex").
   */
  name: string;
  /**
   * Optional base URL override for the provider endpoint.
   */
  url?: string | undefined;
  /**
   * Secret reference the provider authenticates with (e.g. "albus.sh/secrets/my-key"), not a raw secret value.
   *
   * @remarks
   */
  credential: string;
};

/** @internal */
export const Provider$inboundSchema: z.ZodMiniType<Provider, unknown> = z
  .object({
    name: types.string(),
    url: types.optional(types.string()),
    credential: types.string(),
  });
/** @internal */
export type Provider$Outbound = {
  name: string;
  url?: string | undefined;
  credential: string;
};

/** @internal */
export const Provider$outboundSchema: z.ZodMiniType<
  Provider$Outbound,
  Provider
> = z.object({
  name: z.string(),
  url: z.optional(z.string()),
  credential: z.string(),
});

export function providerToJSON(provider: Provider): string {
  return JSON.stringify(Provider$outboundSchema.parse(provider));
}
export function providerFromJSON(
  jsonString: string,
): SafeParseResult<Provider, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Provider$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Provider' from JSON`,
  );
}
