/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type Provider = {
  /**
   * Provider name (e.g. "openai", "gemini", "vertex").
   */
  name: string;
  /**
   * Optional base URL override for the provider endpoint.
   */
  url?: string | undefined;
  /**
   * Secret reference the provider authenticates with (e.g. "albus.sh/secrets/my-key"), not a raw secret value.
   *
   * @remarks
   */
  credential: string;
};

/** @internal */
export type Provider$Outbound = {
  name: string;
  url?: string | undefined;
  credential: string;
};

/** @internal */
export const Provider$outboundSchema: z.ZodMiniType<
  Provider$Outbound,
  Provider
> = z.object({
  name: z.string(),
  url: z.optional(z.string()),
  credential: z.string(),
});

export function providerToJSON(provider: Provider): string {
  return JSON.stringify(Provider$outboundSchema.parse(provider));
}
