/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * A member's role in an organization.
 */
export const Role = {
  Admin: "admin",
  Member: "member",
} as const;
/**
 * A member's role in an organization.
 */
export type Role = OpenEnum<typeof Role>;

/** @internal */
export const Role$inboundSchema: z.ZodMiniType<Role, unknown> = openEnums
  .inboundSchema(Role);
/** @internal */
export const Role$outboundSchema: z.ZodMiniType<string, Role> = openEnums
  .outboundSchema(Role);
