/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  AgentConfig,
  AgentConfig$Outbound,
  AgentConfig$outboundSchema,
} from "./agent-config.js";

export type RunSessionRequest = {
  /**
   * The user prompt driving this invocation.
   */
  userPrompt: string;
  /**
   * Human-readable name identifying the agent (e.g. "support-triage"). Runs sharing a name are grouped as one agent; each distinct configuration under it becomes a revision.
   *
   * @remarks
   */
  agentName: string;
  /**
   * The agent configuration for a run: the model, tools, instructions, and MCP servers that define its behavior. Runs with the same configuration share a revision.
   *
   * @remarks
   */
  agent: AgentConfig;
};

/** @internal */
export type RunSessionRequest$Outbound = {
  user_prompt: string;
  agent_name: string;
  agent: AgentConfig$Outbound;
};

/** @internal */
export const RunSessionRequest$outboundSchema: z.ZodMiniType<
  RunSessionRequest$Outbound,
  RunSessionRequest
> = z.pipe(
  z.object({
    userPrompt: z.string(),
    agentName: z.string(),
    agent: AgentConfig$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      userPrompt: "user_prompt",
      agentName: "agent_name",
    });
  }),
);

export function runSessionRequestToJSON(
  runSessionRequest: RunSessionRequest,
): string {
  return JSON.stringify(
    RunSessionRequest$outboundSchema.parse(runSessionRequest),
  );
}
