/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  MCPServer,
  MCPServer$Outbound,
  MCPServer$outboundSchema,
} from "./mcp-server.js";
import { Model, Model$Outbound, Model$outboundSchema } from "./model.js";

export type RunSessionRequest = {
  /**
   * The user prompt driving this invocation.
   */
  userPrompt: string;
  model: Model;
  /**
   * Names of the tools the model may call (e.g. "WEB_SEARCH").
   */
  tools?: Array<string> | undefined;
  /**
   * System instructions for the model. Uses a default if omitted.
   */
  systemPrompt?: string | undefined;
  /**
   * Max model steps before the run stops. Uses a default if omitted.
   */
  maxSteps?: number | undefined;
  /**
   * MCP servers whose tools are offered to the model.
   */
  mcpServers?: Array<MCPServer> | undefined;
};

/** @internal */
export type RunSessionRequest$Outbound = {
  user_prompt: string;
  model: Model$Outbound;
  tools?: Array<string> | undefined;
  system_prompt?: string | undefined;
  max_steps?: number | undefined;
  mcp_servers?: Array<MCPServer$Outbound> | undefined;
};

/** @internal */
export const RunSessionRequest$outboundSchema: z.ZodMiniType<
  RunSessionRequest$Outbound,
  RunSessionRequest
> = z.pipe(
  z.object({
    userPrompt: z.string(),
    model: Model$outboundSchema,
    tools: z.optional(z.array(z.string())),
    systemPrompt: z.optional(z.string()),
    maxSteps: z.optional(z.int()),
    mcpServers: z.optional(z.array(MCPServer$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      userPrompt: "user_prompt",
      systemPrompt: "system_prompt",
      maxSteps: "max_steps",
      mcpServers: "mcp_servers",
    });
  }),
);

export function runSessionRequestToJSON(
  runSessionRequest: RunSessionRequest,
): string {
  return JSON.stringify(
    RunSessionRequest$outboundSchema.parse(runSessionRequest),
  );
}
