/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SessionMessage,
  SessionMessage$inboundSchema,
} from "./session-message.js";
import { Session, Session$inboundSchema } from "./session.js";

export type RunSessionResponse = {
  session: Session;
  /**
   * The assistant message this invocation produced. Absent when the invocation has not answered yet — a call with `wait_timeout_seconds=0`, or a wait that returned before the response existed. Use `GET /sessions/{id}` to read it later.
   *
   * @remarks
   */
  message?: SessionMessage | undefined;
};

/** @internal */
export const RunSessionResponse$inboundSchema: z.ZodMiniType<
  RunSessionResponse,
  unknown
> = z.object({
  session: Session$inboundSchema,
  message: types.optional(SessionMessage$inboundSchema),
});

export function runSessionResponseFromJSON(
  jsonString: string,
): SafeParseResult<RunSessionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RunSessionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RunSessionResponse' from JSON`,
  );
}
