/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Secret = {
  name: string;
  /**
   * The secret value with all but the last 3 characters masked.
   */
  maskedValue: string;
};

/** @internal */
export const Secret$inboundSchema: z.ZodMiniType<Secret, unknown> = z.pipe(
  z.object({
    name: types.string(),
    masked_value: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "masked_value": "maskedValue",
    });
  }),
);

export function secretFromJSON(
  jsonString: string,
): SafeParseResult<Secret, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Secret$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Secret' from JSON`,
  );
}
