/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SessionMessage,
  SessionMessage$inboundSchema,
} from "./session-message.js";
import { Session, Session$inboundSchema } from "./session.js";

export type SessionResponse = {
  session: Session;
  messages: Array<SessionMessage>;
};

/** @internal */
export const SessionResponse$inboundSchema: z.ZodMiniType<
  SessionResponse,
  unknown
> = z.object({
  session: Session$inboundSchema,
  messages: z.array(SessionMessage$inboundSchema),
});

export function sessionResponseFromJSON(
  jsonString: string,
): SafeParseResult<SessionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SessionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SessionResponse' from JSON`,
  );
}
