/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { SessionState, SessionState$inboundSchema } from "./session-state.js";

export type Session = {
  /**
   * Client-provided session identifier.
   */
  id: string;
  /**
   * Lifecycle state of the session: `RUNNING` while an invocation is in flight, otherwise how its latest invocation ended.
   *
   * @remarks
   */
  state: SessionState;
  /**
   * The key of the invocation currently running, if any. Omitted when the session is idle.
   *
   * @remarks
   */
  currentInvocationKey?: string | undefined;
  /**
   * Number of invocations in this session.
   */
  invocationCount: number;
  /**
   * Name of the agent that last ran this session.
   */
  agentName?: string | undefined;
  /**
   * Revision of the agent that last ran this session. Invocations with the same configuration share this value.
   *
   * @remarks
   */
  agentRevision?: string | undefined;
  createdAt: Date;
  updatedAt: Date;
  /**
   * When the session was deleted. A deleted session keeps its audit log but accepts no new invocations. Omitted while the session is live.
   *
   * @remarks
   */
  deletedAt?: Date | undefined;
};

/** @internal */
export const Session$inboundSchema: z.ZodMiniType<Session, unknown> = z.pipe(
  z.object({
    id: types.string(),
    state: SessionState$inboundSchema,
    current_invocation_key: types.optional(types.string()),
    invocation_count: types.number(),
    agent_name: types.optional(types.string()),
    agent_revision: types.optional(types.string()),
    created_at: types.date(),
    updated_at: types.date(),
    deleted_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "current_invocation_key": "currentInvocationKey",
      "invocation_count": "invocationCount",
      "agent_name": "agentName",
      "agent_revision": "agentRevision",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "deleted_at": "deletedAt",
    });
  }),
);

export function sessionFromJSON(
  jsonString: string,
): SafeParseResult<Session, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Session$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Session' from JSON`,
  );
}
