/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const SessionMessageRole = {
  User: "user",
  Assistant: "assistant",
} as const;
export type SessionMessageRole = OpenEnum<typeof SessionMessageRole>;

export type SessionMessage = {
  /**
   * Position of this message in the session's history, ascending — not an index into the list it arrives in.
   *
   * @remarks
   */
  cursor: number;
  /**
   * The invocation that produced this message.
   */
  invocationId: string;
  role: SessionMessageRole;
  content: string;
  createdAt: Date;
};

/** @internal */
export const SessionMessageRole$inboundSchema: z.ZodMiniType<
  SessionMessageRole,
  unknown
> = openEnums.inboundSchema(SessionMessageRole);

/** @internal */
export const SessionMessage$inboundSchema: z.ZodMiniType<
  SessionMessage,
  unknown
> = z.pipe(
  z.object({
    cursor: types.number(),
    invocation_id: types.string(),
    role: SessionMessageRole$inboundSchema,
    content: types.string(),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "invocation_id": "invocationId",
      "created_at": "createdAt",
    });
  }),
);

export function sessionMessageFromJSON(
  jsonString: string,
): SafeParseResult<SessionMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SessionMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SessionMessage' from JSON`,
  );
}
