/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Lifecycle state of the session: `RUNNING` while an invocation is in flight, otherwise how its latest invocation ended.
 *
 * @remarks
 */
export const SessionState = {
  Running: "RUNNING",
  Done: "DONE",
  Failed: "FAILED",
  Canceled: "CANCELED",
} as const;
/**
 * Lifecycle state of the session: `RUNNING` while an invocation is in flight, otherwise how its latest invocation ended.
 *
 * @remarks
 */
export type SessionState = OpenEnum<typeof SessionState>;

/** @internal */
export const SessionState$inboundSchema: z.ZodMiniType<SessionState, unknown> =
  openEnums.inboundSchema(SessionState);
/** @internal */
export const SessionState$outboundSchema: z.ZodMiniType<string, SessionState> =
  openEnums.outboundSchema(SessionState);
