/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Lifecycle state of the session.
 */
export const State = {
  Running: "RUNNING",
  Done: "DONE",
  Failed: "FAILED",
  Canceled: "CANCELED",
} as const;
/**
 * Lifecycle state of the session.
 */
export type State = OpenEnum<typeof State>;

export type Session = {
  /**
   * Client-provided session identifier.
   */
  id: string;
  /**
   * Lifecycle state of the session.
   */
  state: State;
  /**
   * The invocation currently running, if any. Omitted when the session is idle.
   *
   * @remarks
   */
  currentInvocationId?: string | undefined;
  /**
   * Number of times this session has been run.
   */
  invocationCount: number;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const State$inboundSchema: z.ZodMiniType<State, unknown> = openEnums
  .inboundSchema(State);

/** @internal */
export const Session$inboundSchema: z.ZodMiniType<Session, unknown> = z.pipe(
  z.object({
    id: types.string(),
    state: State$inboundSchema,
    current_invocation_id: types.optional(types.string()),
    invocation_count: types.number(),
    created_at: types.date(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "current_invocation_id": "currentInvocationId",
      "invocation_count": "invocationCount",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function sessionFromJSON(
  jsonString: string,
): SafeParseResult<Session, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Session$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Session' from JSON`,
  );
}
