/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { Role, Role$outboundSchema } from "./role.js";

export type SetOrganizationMemberRoleRequest = {
  /**
   * A member's role in an organization.
   */
  role: Role;
};

/** @internal */
export type SetOrganizationMemberRoleRequest$Outbound = {
  role: string;
};

/** @internal */
export const SetOrganizationMemberRoleRequest$outboundSchema: z.ZodMiniType<
  SetOrganizationMemberRoleRequest$Outbound,
  SetOrganizationMemberRoleRequest
> = z.object({
  role: Role$outboundSchema,
});

export function setOrganizationMemberRoleRequestToJSON(
  setOrganizationMemberRoleRequest: SetOrganizationMemberRoleRequest,
): string {
  return JSON.stringify(
    SetOrganizationMemberRoleRequest$outboundSchema.parse(
      setOrganizationMemberRoleRequest,
    ),
  );
}
