/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * What was used: a model billed to your credits, a model called with your own provider credential, or the compute an invocation ran on.
 *
 * @remarks
 */
export const SpendLineKind = {
  Model: "model",
  ModelByok: "model_byok",
  Hardware: "hardware",
} as const;
/**
 * What was used: a model billed to your credits, a model called with your own provider credential, or the compute an invocation ran on.
 *
 * @remarks
 */
export type SpendLineKind = OpenEnum<typeof SpendLineKind>;

export type SpendLine = {
  /**
   * The UTC midnight starting the day this line covers.
   */
  day: Date;
  /**
   * What was used: a model billed to your credits, a model called with your own provider credential, or the compute an invocation ran on.
   *
   * @remarks
   */
  kind: SpendLineKind;
  /**
   * The provider that served the model. Present on model and model_byok lines.
   *
   * @remarks
   */
  providerName?: string | undefined;
  /**
   * The model that was called. Present on model and model_byok lines.
   *
   * @remarks
   */
  modelName?: string | undefined;
  /**
   * The compute item charged (e.g. "invocation_second"). Present on hardware lines.
   *
   * @remarks
   */
  sku?: string | undefined;
  /**
   * What this line cost, as a decimal USD string. Zero when the usage was free. On a model_byok line this is the usage valued at our model prices for reference; you paid the provider directly and no credits were charged.
   *
   * @remarks
   */
  usd: string;
  /**
   * Prompt tokens sent, including cached ones.
   */
  inputTokens?: number | undefined;
  /**
   * Prompt tokens served from the provider's cache.
   */
  cachedInputTokens?: number | undefined;
  /**
   * Tokens the model generated.
   */
  outputTokens?: number | undefined;
  /**
   * Tokens the model spent reasoning.
   */
  thoughtsTokens?: number | undefined;
  /**
   * Milliseconds of compute time charged.
   */
  wallMs?: number | undefined;
};

/** @internal */
export const SpendLineKind$inboundSchema: z.ZodMiniType<
  SpendLineKind,
  unknown
> = openEnums.inboundSchema(SpendLineKind);

/** @internal */
export const SpendLine$inboundSchema: z.ZodMiniType<SpendLine, unknown> = z
  .pipe(
    z.object({
      day: types.date(),
      kind: SpendLineKind$inboundSchema,
      provider_name: types.optional(types.string()),
      model_name: types.optional(types.string()),
      sku: types.optional(types.string()),
      usd: types.string(),
      input_tokens: types.optional(types.number()),
      cached_input_tokens: types.optional(types.number()),
      output_tokens: types.optional(types.number()),
      thoughts_tokens: types.optional(types.number()),
      wall_ms: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "provider_name": "providerName",
        "model_name": "modelName",
        "input_tokens": "inputTokens",
        "cached_input_tokens": "cachedInputTokens",
        "output_tokens": "outputTokens",
        "thoughts_tokens": "thoughtsTokens",
        "wall_ms": "wallMs",
      });
    }),
  );

export function spendLineFromJSON(
  jsonString: string,
): SafeParseResult<SpendLine, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SpendLine$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SpendLine' from JSON`,
  );
}
