/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { SpendLine, SpendLine$inboundSchema } from "./spend-line.js";

export type SpendResponse = {
  /**
   * The UTC midnight the lines start from, after widening `since` to a whole day.
   *
   * @remarks
   */
  since: Date;
  /**
   * The UTC midnight the lines stop before, after widening `until` to a whole day.
   *
   * @remarks
   */
  until: Date;
  /**
   * The sum of every line charged to your credits, as a decimal USD string. Excludes model_byok lines.
   *
   * @remarks
   */
  totalUsd: string;
  /**
   * Ordered by day, then kind, provider, model, and sku.
   */
  lines: Array<SpendLine>;
};

/** @internal */
export const SpendResponse$inboundSchema: z.ZodMiniType<
  SpendResponse,
  unknown
> = z.pipe(
  z.object({
    since: types.date(),
    until: types.date(),
    total_usd: types.string(),
    lines: z.array(SpendLine$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "total_usd": "totalUsd",
    });
  }),
);

export function spendResponseFromJSON(
  jsonString: string,
): SafeParseResult<SpendResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SpendResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SpendResponse' from JSON`,
  );
}
