/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Offers the model a persistent Linux sandbox to run commands in.
 *
 * @remarks
 */
export type TerminalTool = {};

/** @internal */
export const TerminalTool$inboundSchema: z.ZodMiniType<TerminalTool, unknown> =
  z.object({});
/** @internal */
export type TerminalTool$Outbound = {};

/** @internal */
export const TerminalTool$outboundSchema: z.ZodMiniType<
  TerminalTool$Outbound,
  TerminalTool
> = z.object({});

export function terminalToolToJSON(terminalTool: TerminalTool): string {
  return JSON.stringify(TerminalTool$outboundSchema.parse(terminalTool));
}
export function terminalToolFromJSON(
  jsonString: string,
): SafeParseResult<TerminalTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TerminalTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TerminalTool' from JSON`,
  );
}
