/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * API token metadata. Never includes the token value.
 */
export type Token = {
  /**
   * Globally unique lookup identifier (the first segment of the token string).
   */
  id: string;
  /**
   * Human-readable display name for the token.
   */
  name: string;
  createdAt: Date;
  /**
   * Timestamp of the last time this token was used for authentication.
   */
  lastUsedAt?: Date | undefined;
};

/** @internal */
export const Token$inboundSchema: z.ZodMiniType<Token, unknown> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    created_at: types.date(),
    last_used_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "last_used_at": "lastUsedAt",
    });
  }),
);

export function tokenFromJSON(
  jsonString: string,
): SafeParseResult<Token, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Token$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Token' from JSON`,
  );
}
