/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Tokens consumed. Absent when none were recorded.
 */
export type TokenUsage = {
  inputTokens?: number | undefined;
  outputTokens?: number | undefined;
  totalTokens?: number | undefined;
  /**
   * Tokens the model spent reasoning before it answered, as reported by the provider. Absent when the provider reports none.
   *
   * @remarks
   */
  thinkingTokens?: number | undefined;
};

/** @internal */
export const TokenUsage$inboundSchema: z.ZodMiniType<TokenUsage, unknown> = z
  .pipe(
    z.object({
      input_tokens: types.optional(types.number()),
      output_tokens: types.optional(types.number()),
      total_tokens: types.optional(types.number()),
      thinking_tokens: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "input_tokens": "inputTokens",
        "output_tokens": "outputTokens",
        "total_tokens": "totalTokens",
        "thinking_tokens": "thinkingTokens",
      });
    }),
  );

export function tokenUsageFromJSON(
  jsonString: string,
): SafeParseResult<TokenUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TokenUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TokenUsage' from JSON`,
  );
}
