/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ComputerTool,
  ComputerTool$inboundSchema,
  ComputerTool$Outbound,
  ComputerTool$outboundSchema,
} from "./computer-tool.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WebSearchTool,
  WebSearchTool$inboundSchema,
  WebSearchTool$Outbound,
  WebSearchTool$outboundSchema,
} from "./web-search-tool.js";

/**
 * The built-in tools the model may call. Include a tool's block to offer it (e.g. {"web_search": {}}); omit it to withhold it.
 *
 * @remarks
 */
export type Tools = {
  /**
   * Offers the model web search.
   */
  webSearch?: WebSearchTool | undefined;
  /**
   * Offers the model a persistent Linux sandbox to run commands in.
   *
   * @remarks
   */
  computer?: ComputerTool | undefined;
};

/** @internal */
export const Tools$inboundSchema: z.ZodMiniType<Tools, unknown> = z.pipe(
  z.object({
    web_search: types.optional(WebSearchTool$inboundSchema),
    computer: types.optional(ComputerTool$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "web_search": "webSearch",
    });
  }),
);
/** @internal */
export type Tools$Outbound = {
  web_search?: WebSearchTool$Outbound | undefined;
  computer?: ComputerTool$Outbound | undefined;
};

/** @internal */
export const Tools$outboundSchema: z.ZodMiniType<Tools$Outbound, Tools> = z
  .pipe(
    z.object({
      webSearch: z.optional(WebSearchTool$outboundSchema),
      computer: z.optional(ComputerTool$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        webSearch: "web_search",
      });
    }),
  );

export function toolsToJSON(tools: Tools): string {
  return JSON.stringify(Tools$outboundSchema.parse(tools));
}
export function toolsFromJSON(
  jsonString: string,
): SafeParseResult<Tools, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Tools$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Tools' from JSON`,
  );
}
