/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { TraceStatus, TraceStatus$inboundSchema } from "./trace-status.js";

/**
 * One agent invocation — what it ran, how it ended, and when.
 */
export type TraceSummary = {
  /**
   * The invocation's key — the value sent as its Idempotency-Key, or the one the server returned in that header when it was omitted.
   *
   * @remarks
   */
  invocationKey: string;
  /**
   * The session this invocation belongs to.
   */
  sessionId: string;
  /**
   * Name of the agent the invocation ran (e.g. "support-triage"). Absent for an invocation made before agent names were recorded.
   *
   * @remarks
   */
  agentName?: string | undefined;
  /**
   * The agent revision the invocation ran (e.g. "a1b2c3d4"). Absent for an invocation made before revisions were recorded.
   *
   * @remarks
   */
  agentRevision?: string | undefined;
  /**
   * How an invocation or one of its attempts ended, or `RUNNING` while it is still in flight.
   *
   * @remarks
   */
  status: TraceStatus;
  /**
   * Whether the invocation's spans have aged out. Spans are kept for the retention window (currently 90 days) from the invocation's start; the invocation itself is kept, so `status` and the fields beside it stay readable past it.
   *
   * @remarks
   */
  spansExpired: boolean;
  /**
   * When the invocation was accepted.
   */
  startedAt: Date;
  /**
   * When the invocation's outcome was recorded. Absent while it runs.
   *
   * @remarks
   */
  endedAt?: Date | undefined;
};

/** @internal */
export const TraceSummary$inboundSchema: z.ZodMiniType<TraceSummary, unknown> =
  z.pipe(
    z.object({
      invocation_key: types.string(),
      session_id: types.string(),
      agent_name: types.optional(types.string()),
      agent_revision: types.optional(types.string()),
      status: TraceStatus$inboundSchema,
      spans_expired: types.boolean(),
      started_at: types.date(),
      ended_at: types.optional(types.date()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "invocation_key": "invocationKey",
        "session_id": "sessionId",
        "agent_name": "agentName",
        "agent_revision": "agentRevision",
        "spans_expired": "spansExpired",
        "started_at": "startedAt",
        "ended_at": "endedAt",
      });
    }),
  );

export function traceSummaryFromJSON(
  jsonString: string,
): SafeParseResult<TraceSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TraceSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TraceSummary' from JSON`,
  );
}
