/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Why an invocation failed, and what to show for it.
 */
export type TraceFailure = {
  /**
   * Failure classification: "crash" (unexpected exit or signal), "no_progress" (the harness stalled and was force-killed), "interrupted" (the invocation could not continue), or "internal" (the invocation could not start).
   *
   * @remarks
   */
  kind: string;
  /**
   * The sentence recorded for this failure.
   */
  message: string;
};

/** @internal */
export const TraceFailure$inboundSchema: z.ZodMiniType<TraceFailure, unknown> =
  z.object({
    kind: types.string(),
    message: types.string(),
  });

export function traceFailureFromJSON(
  jsonString: string,
): SafeParseResult<TraceFailure, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TraceFailure$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TraceFailure' from JSON`,
  );
}
