/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { TokenUsage, TokenUsage$inboundSchema } from "./token-usage.js";

/**
 * The kind of span (e.g. "invocation" for the invocation itself, "step" for one step, "model_call" for a model call, "tool_call" for a tool call it requested).
 *
 * @remarks
 */
export const TraceSpanType = {
  Invocation: "invocation",
  Step: "step",
  ModelCall: "model_call",
  ToolCall: "tool_call",
} as const;
/**
 * The kind of span (e.g. "invocation" for the invocation itself, "step" for one step, "model_call" for a model call, "tool_call" for a tool call it requested).
 *
 * @remarks
 */
export type TraceSpanType = OpenEnum<typeof TraceSpanType>;

/**
 * Whether the span succeeded. Only finished spans are returned.
 *
 * @remarks
 */
export const TraceSpanStatus = {
  Succeeded: "SUCCEEDED",
  Failed: "FAILED",
} as const;
/**
 * Whether the span succeeded. Only finished spans are returned.
 *
 * @remarks
 */
export type TraceSpanStatus = OpenEnum<typeof TraceSpanStatus>;

/**
 * One span of an invocation — a model call, a tool call it requested, or a level of the invocation above them.
 *
 * @remarks
 */
export type TraceSpan = {
  /**
   * Where the span sits in its session, as a dotted path you can read: `inv2` is the invocation itself — the second invocation of its session — `inv2.attempt1.step3` one step of it, a model call and the tool calls it requested, `inv2.attempt1.step3.model` that step's model call, and `inv2.attempt1.step3.tool1` a tool call it requested, numbered in the order it requested them. Every count starts at 1, no segment is ever `0`, and `.model` is a slot rather than a count, so a step has exactly one. `inv2.attempt1` is not a span you can fetch: an attempt is not a span, so a step's parent is the invocation, and only a model or tool call's parent is its own id without its last segment. The attempt segment is what keeps an id from being reused: the same step of a second attempt is `inv2.attempt2.step3`, never a fresh `inv2.attempt1.step3` under an id you have already read. An id comes from the span itself, not from the page or the attempts you asked for, so the same span has the same id on every page, under `attempts=final` and under `attempts=all`, and across requests. Ids are unique within a session, so the spans of several of a session's invocations read as one tree with the session as its root.
   *
   * @remarks
   */
  id: string;
  /**
   * Id of the span this one belongs to: for a model call or a tool call, this span's id without its last segment; for a step, the invocation itself — an attempt is not a span. Absent only for the invocation. It is present even when the span it names is not in this response: the invocation is published once it has ended and a step once that step has ended, so a still-running invocation has spans whose parent is not there yet, which is not an error. Treat a parent you cannot find as one you do not have.
   *
   * @remarks
   */
  parentId?: string | undefined;
  /**
   * Which attempt of the invocation this span belongs to, counting from 1 — the same number as the second segment of its `id`, so a retry is visible without reading the id. Absent on the invocation itself, which belongs to no single attempt.
   *
   * @remarks
   */
  attempt?: number | undefined;
  /**
   * Whether this span belongs to an attempt that was tried again, so nothing it produced reached the invocation's output. Only `attempts=all` returns such spans, and what they did still stands: their tokens were spent and their tool calls had their effects. Absent on a span of the latest attempt.
   *
   * @remarks
   */
  superseded?: boolean | undefined;
  /**
   * The kind of span (e.g. "invocation" for the invocation itself, "step" for one step, "model_call" for a model call, "tool_call" for a tool call it requested).
   *
   * @remarks
   */
  type: TraceSpanType;
  /**
   * The model or tool the span called (e.g. "WEB_SEARCH"). Absent for a span that called neither.
   *
   * @remarks
   */
  name?: string | undefined;
  /**
   * Whether the span succeeded. Only finished spans are returned.
   *
   * @remarks
   */
  status: TraceSpanStatus;
  /**
   * Why the span failed. Absent when it succeeded. A long message is shortened, and then carries the same `[omitted: N of M bytes; sha256=…]` marker a payload does.
   *
   * @remarks
   */
  error?: string | undefined;
  /**
   * When the span began.
   */
  startedAt: Date;
  /**
   * When the span finished.
   */
  endedAt: Date;
  /**
   * Tokens consumed. Absent when none were recorded.
   */
  usage?: TokenUsage | undefined;
  /**
   * What the span was given. A shortened value carries its head and tail separated by a `[omitted: N of M bytes; sha256=…]` marker; a model call's payloads are left out entirely when the span records too much to keep. A tool call's input is the one that comes with `input_bytes` and `input_sha256`.
   *
   * @remarks
   */
  input?: string | undefined;
  /**
   * Size of the complete input, when known.
   *
   * @remarks
   */
  inputBytes?: number | undefined;
  /**
   * SHA-256 of the complete input, when known.
   *
   * @remarks
   */
  inputSha256?: string | undefined;
  /**
   * Whether `input` is shortened or left out, when known. A left-out payload carries neither `input_bytes` nor `input_sha256`; the invocation's own shortened input carries no `input_truncated` either.
   *
   * @remarks
   */
  inputTruncated?: boolean | undefined;
  /**
   * What the span returned. A shortened value carries its head and tail separated by a `[omitted: N of M bytes; sha256=…]` marker; a model call's payloads are left out entirely when the span records too much to keep. A tool call's output is the one that comes with `output_bytes` and `output_sha256`.
   *
   * @remarks
   */
  output?: string | undefined;
  /**
   * Size of the complete output, when known.
   *
   * @remarks
   */
  outputBytes?: number | undefined;
  /**
   * SHA-256 of the complete output, when known.
   *
   * @remarks
   */
  outputSha256?: string | undefined;
  /**
   * Whether `output` is shortened or left out, when known. A left-out payload carries neither `output_bytes` nor `output_sha256`; the invocation's own shortened output carries no `output_truncated` either.
   *
   * @remarks
   */
  outputTruncated?: boolean | undefined;
};

/** @internal */
export const TraceSpanType$inboundSchema: z.ZodMiniType<
  TraceSpanType,
  unknown
> = openEnums.inboundSchema(TraceSpanType);

/** @internal */
export const TraceSpanStatus$inboundSchema: z.ZodMiniType<
  TraceSpanStatus,
  unknown
> = openEnums.inboundSchema(TraceSpanStatus);

/** @internal */
export const TraceSpan$inboundSchema: z.ZodMiniType<TraceSpan, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      parent_id: types.optional(types.string()),
      attempt: types.optional(types.number()),
      superseded: types.optional(types.boolean()),
      type: TraceSpanType$inboundSchema,
      name: types.optional(types.string()),
      status: TraceSpanStatus$inboundSchema,
      error: types.optional(types.string()),
      started_at: types.date(),
      ended_at: types.date(),
      usage: types.optional(TokenUsage$inboundSchema),
      input: types.optional(types.string()),
      input_bytes: types.optional(types.number()),
      input_sha256: types.optional(types.string()),
      input_truncated: types.optional(types.boolean()),
      output: types.optional(types.string()),
      output_bytes: types.optional(types.number()),
      output_sha256: types.optional(types.string()),
      output_truncated: types.optional(types.boolean()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "parent_id": "parentId",
        "started_at": "startedAt",
        "ended_at": "endedAt",
        "input_bytes": "inputBytes",
        "input_sha256": "inputSha256",
        "input_truncated": "inputTruncated",
        "output_bytes": "outputBytes",
        "output_sha256": "outputSha256",
        "output_truncated": "outputTruncated",
      });
    }),
  );

export function traceSpanFromJSON(
  jsonString: string,
): SafeParseResult<TraceSpan, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TraceSpan$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TraceSpan' from JSON`,
  );
}
