/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { TokenUsage, TokenUsage$inboundSchema } from "./token-usage.js";
import { TraceStatus, TraceStatus$inboundSchema } from "./trace-status.js";

/**
 * One attempt of an invocation. An invocation is attempted again when an attempt cannot be finished, and every attempt starts the agent's work over: an attempt before the last one spent its own tokens and may have made tool calls whose effects stand, even though nothing it produced reached the invocation's output.
 *
 * @remarks
 */
export type TraceAttempt = {
  /**
   * Which attempt this is, counting from 1. The last one is the attempt that produced the invocation's outcome, or the one still in flight, and the one whose spans come back unless `attempts=all` is requested.
   *
   * @remarks
   */
  attempt: number;
  /**
   * How an invocation or one of its attempts ended, or `RUNNING` while it is still in flight.
   *
   * @remarks
   */
  status: TraceStatus;
  /**
   * When the attempt began.
   */
  startedAt: Date;
  /**
   * When the attempt ended. Absent while it runs.
   */
  endedAt?: Date | undefined;
  /**
   * Tokens consumed. Absent when none were recorded.
   */
  usage?: TokenUsage | undefined;
};

/** @internal */
export const TraceAttempt$inboundSchema: z.ZodMiniType<TraceAttempt, unknown> =
  z.pipe(
    z.object({
      attempt: types.number(),
      status: TraceStatus$inboundSchema,
      started_at: types.date(),
      ended_at: types.optional(types.date()),
      usage: types.optional(TokenUsage$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        "started_at": "startedAt",
        "ended_at": "endedAt",
      });
    }),
  );

export function traceAttemptFromJSON(
  jsonString: string,
): SafeParseResult<TraceAttempt, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TraceAttempt$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TraceAttempt' from JSON`,
  );
}
