/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { TraceAttempt, TraceAttempt$inboundSchema } from "./trace-attempt.js";
import { TraceFailure, TraceFailure$inboundSchema } from "./trace-failure.js";
import { TraceSpan, TraceSpan$inboundSchema } from "./trace-span.js";
import { TraceStatus, TraceStatus$inboundSchema } from "./trace-status.js";

/**
 * One agent invocation — what it ran, how it ended, and when.
 */
export type TraceResponse = {
  /**
   * The invocation's key — the value sent as its Idempotency-Key, or the one the server returned in that header when it was omitted.
   *
   * @remarks
   */
  invocationKey: string;
  /**
   * The session this invocation belongs to.
   */
  sessionId: string;
  /**
   * Name of the agent the invocation ran (e.g. "support-triage"). Absent for an invocation made before agent names were recorded.
   *
   * @remarks
   */
  agentName?: string | undefined;
  /**
   * The agent revision the invocation ran (e.g. "a1b2c3d4"). Absent for an invocation made before revisions were recorded.
   *
   * @remarks
   */
  agentRevision?: string | undefined;
  /**
   * How an invocation or one of its attempts ended, or `RUNNING` while it is still in flight. `CANCELED` means it was stopped on request before it answered.
   *
   * @remarks
   */
  status: TraceStatus;
  /**
   * Whether the invocation's spans have aged out. Spans are kept for the retention window (currently 90 days) from the invocation's start; the invocation itself is kept, so `status` and the fields beside it stay readable past it.
   *
   * @remarks
   */
  spansExpired: boolean;
  /**
   * When the invocation was accepted.
   */
  startedAt: Date;
  /**
   * When the invocation's outcome was recorded. Absent while it runs.
   *
   * @remarks
   */
  endedAt?: Date | undefined;
  /**
   * Why the invocation ended without answering. Present only when `status` is `FAILED` or `CANCELED`, and readable past the retention window, since it comes from the invocation rather than its spans. Read it here rather than from `GET /traces`, which reports only that an invocation failed — listing a page of reasons costs a lookup per invocation on it.
   *
   * @remarks
   */
  failure?: TraceFailure | undefined;
  /**
   * Which invocation of its session this is, counting from 1 in the order they were created — the same number as the `inv` segment of every span's id, so you do not have to read an id to know which invocation you are holding. Invocations are only ever appended, so a position never changes.
   *
   * @remarks
   */
  sessionPosition: number;
  /**
   * A page of the invocation's spans, oldest first, from its latest attempt unless `attempts=all` asked for the earlier attempts as well. It can hold fewer than `limit`, or none at all, while `next_cursor` is present. Empty once `spans_expired` is true.
   *
   * @remarks
   */
  spans: Array<TraceSpan>;
  /**
   * Every attempt of the invocation, oldest first, whichever attempts `spans` came from — so one entry means it ran once, and more than one means the attempts before the last produced nothing that reached its output, while still spending tokens and making any tool calls they made. Read them with `attempts=all`. Absent once `spans_expired` is true.
   *
   * @remarks
   */
  attempts?: Array<TraceAttempt> | undefined;
  /**
   * Cursor for the next page. Pass it as `after` to fetch the following spans. Present whenever there may be more spans, however few this page returned; omitted once there are none left, including once `spans_expired` is true.
   *
   * @remarks
   */
  nextCursor?: string | undefined;
};

/** @internal */
export const TraceResponse$inboundSchema: z.ZodMiniType<
  TraceResponse,
  unknown
> = z.pipe(
  z.object({
    invocation_key: types.string(),
    session_id: types.string(),
    agent_name: types.optional(types.string()),
    agent_revision: types.optional(types.string()),
    status: TraceStatus$inboundSchema,
    spans_expired: types.boolean(),
    started_at: types.date(),
    ended_at: types.optional(types.date()),
    failure: types.optional(TraceFailure$inboundSchema),
    session_position: types.number(),
    spans: z.array(TraceSpan$inboundSchema),
    attempts: types.optional(z.array(TraceAttempt$inboundSchema)),
    next_cursor: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "invocation_key": "invocationKey",
      "session_id": "sessionId",
      "agent_name": "agentName",
      "agent_revision": "agentRevision",
      "spans_expired": "spansExpired",
      "started_at": "startedAt",
      "ended_at": "endedAt",
      "session_position": "sessionPosition",
      "next_cursor": "nextCursor",
    });
  }),
);

export function traceResponseFromJSON(
  jsonString: string,
): SafeParseResult<TraceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TraceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TraceResponse' from JSON`,
  );
}
