/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * How an invocation or one of its attempts ended, or `RUNNING` while it is still in flight.
 *
 * @remarks
 */
export const TraceStatus = {
  Running: "RUNNING",
  Succeeded: "SUCCEEDED",
  Failed: "FAILED",
} as const;
/**
 * How an invocation or one of its attempts ended, or `RUNNING` while it is still in flight.
 *
 * @remarks
 */
export type TraceStatus = OpenEnum<typeof TraceStatus>;

/** @internal */
export const TraceStatus$inboundSchema: z.ZodMiniType<TraceStatus, unknown> =
  openEnums.inboundSchema(TraceStatus);
/** @internal */
export const TraceStatus$outboundSchema: z.ZodMiniType<string, TraceStatus> =
  openEnums.outboundSchema(TraceStatus);
