/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UpdateOrganizationRequest = {
  /**
   * New organization display name.
   */
  name: string;
};

/** @internal */
export type UpdateOrganizationRequest$Outbound = {
  name: string;
};

/** @internal */
export const UpdateOrganizationRequest$outboundSchema: z.ZodMiniType<
  UpdateOrganizationRequest$Outbound,
  UpdateOrganizationRequest
> = z.object({
  name: z.string(),
});

export function updateOrganizationRequestToJSON(
  updateOrganizationRequest: UpdateOrganizationRequest,
): string {
  return JSON.stringify(
    UpdateOrganizationRequest$outboundSchema.parse(updateOrganizationRequest),
  );
}
