/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UpdateSecretRequest = {
  /**
   * The new secret value.
   */
  value: string;
};

/** @internal */
export type UpdateSecretRequest$Outbound = {
  value: string;
};

/** @internal */
export const UpdateSecretRequest$outboundSchema: z.ZodMiniType<
  UpdateSecretRequest$Outbound,
  UpdateSecretRequest
> = z.object({
  value: z.string(),
});

export function updateSecretRequestToJSON(
  updateSecretRequest: UpdateSecretRequest,
): string {
  return JSON.stringify(
    UpdateSecretRequest$outboundSchema.parse(updateSecretRequest),
  );
}
