/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Offers the model web search.
 */
export type WebSearchTool = {};

/** @internal */
export const WebSearchTool$inboundSchema: z.ZodMiniType<
  WebSearchTool,
  unknown
> = z.object({});
/** @internal */
export type WebSearchTool$Outbound = {};

/** @internal */
export const WebSearchTool$outboundSchema: z.ZodMiniType<
  WebSearchTool$Outbound,
  WebSearchTool
> = z.object({});

export function webSearchToolToJSON(webSearchTool: WebSearchTool): string {
  return JSON.stringify(WebSearchTool$outboundSchema.parse(webSearchTool));
}
export function webSearchToolFromJSON(
  jsonString: string,
): SafeParseResult<WebSearchTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebSearchTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebSearchTool' from JSON`,
  );
}
