/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  OrganizationMembership,
  OrganizationMembership$inboundSchema,
} from "./organization-membership.js";

export type WhoamiResponse = {
  /**
   * Unique user identifier
   */
  userId: string;
  /**
   * User's email address
   */
  email: string;
  /**
   * User's display name
   */
  name?: string | undefined;
  /**
   * Roles in the active organization (present only when a single organization is in scope).
   *
   * @remarks
   */
  roles?: Array<string> | undefined;
  /**
   * The organization this session is scoped to. Present when the user belongs to exactly one organization; absent when they belong to several and none is selected yet.
   *
   * @remarks
   */
  activeOrganization?: OrganizationMembership | undefined;
  /**
   * Every organization the user belongs to, with their roles.
   */
  organizations: Array<OrganizationMembership>;
  /**
   * Token issue timestamp (Unix epoch)
   */
  issuedAt?: number | undefined;
  /**
   * Token expiration timestamp (Unix epoch)
   */
  expiresAt?: number | undefined;
};

/** @internal */
export const WhoamiResponse$inboundSchema: z.ZodMiniType<
  WhoamiResponse,
  unknown
> = z.pipe(
  z.object({
    user_id: types.string(),
    email: types.string(),
    name: types.optional(types.string()),
    roles: types.optional(z.array(types.string())),
    active_organization: types.optional(OrganizationMembership$inboundSchema),
    organizations: z.array(OrganizationMembership$inboundSchema),
    issued_at: types.optional(types.number()),
    expires_at: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "user_id": "userId",
      "active_organization": "activeOrganization",
      "issued_at": "issuedAt",
      "expires_at": "expiresAt",
    });
  }),
);

export function whoamiResponseFromJSON(
  jsonString: string,
): SafeParseResult<WhoamiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WhoamiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WhoamiResponse' from JSON`,
  );
}
