/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AuthenticatedApiKey,
  AuthenticatedApiKey$inboundSchema,
} from "./authenticated-api-key.js";
import {
  AuthenticatedUser,
  AuthenticatedUser$inboundSchema,
} from "./authenticated-user.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * The caller a credential authenticates. Exactly one of user or api_key is present.
 *
 * @remarks
 */
export type WhoamiResponse = {
  /**
   * The signed-in user, when calling with a user session.
   */
  user?: AuthenticatedUser | undefined;
  /**
   * The API key, when calling with an API key.
   */
  apiKey?: AuthenticatedApiKey | undefined;
};

/** @internal */
export const WhoamiResponse$inboundSchema: z.ZodMiniType<
  WhoamiResponse,
  unknown
> = z.pipe(
  z.object({
    user: types.optional(AuthenticatedUser$inboundSchema),
    api_key: types.optional(AuthenticatedApiKey$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "api_key": "apiKey",
    });
  }),
);

export function whoamiResponseFromJSON(
  jsonString: string,
): SafeParseResult<WhoamiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WhoamiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WhoamiResponse' from JSON`,
  );
}
